import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import {CARDS,ADVANCED,EVENTS,MARKET_LIMITS,getCard,marketLane} from '../src/cards.js';
import {hours} from '../src/card-visuals.js';
const make=o=>E.createGame({playerCount:3,mode:'hotseat',...o});
function quiet(g){g.inspection={name:'测试平静周',kind:'quiet',times:[],blockedTimes:[]};g.players.forEach(p=>p.tempWeekend=false);return g;}
function add(g,p,type){const c={uid:`c${++g.uid}`,type};p.cards.push(c);return c;}
function skills(g,p,pattern){for(const r of pattern){const d=CARDS.find(d=>d.skill===r&&!p.skills.some(c=>c.type===d.id));p.skills.push({uid:`c${++g.uid}`,type:d.id});}E.syncSanity(g,p);}
function turn(g,id=0){while(g.phase==='planning'&&E.activeBuyer(g)!==id)E.pass(g,E.activeBuyer(g));}
function finish(g){while(g.phase==='planning')E.pass(g,E.activeBuyer(g));E.resolveAll(g);}
function next(g){for(const p of g.players){E.botDraft(g,p.id);if(!Object.hasOwn(g.escapeDecisions,p.id))E.chooseEscape(g,p.id,false);}E.closeWeek(g);}
const am={day:6,period:0},pm={day:6,period:1},night={day:6,period:2};
function allCards(g){return [...Object.values(g.decks).flat(),...Object.values(g.market).flat(),...Object.values(g.discard).flat(),...g.players.flatMap(p=>[...p.cards,...p.completedProjects,...p.skills,...p.upgrades,...p.drafts.flatMap(d=>d.options||[])])];}

test('2/4/8h decks, 5/4/3 market, 57 types, no sanity gain/cost/power anywhere',()=>{const g=make();assert.deepEqual(Object.keys(g.decks),['2','4','8']);assert.equal(CARDS.length+ADVANCED.length,57);for(const [key,n]of Object.entries(MARKET_LIMITS))assert.equal(g.market[key].length,n);assert.ok(ADVANCED.every(d=>hours(d.size)===8));assert.ok([...CARDS,...ADVANCED].every(d=>!Object.hasOwn(d.gain,'sanity')&&!Object.hasOwn(d.cost,'sanity')&&!Object.hasOwn(d.price,'sanity')));assert.ok(ADVANCED.every(d=>!d.powerSanity));assert.equal(g.players[0].sanity,3);assert.equal(g.version,9);});
test('8 of 12 events are inspections, three unique public times each',()=>{const es=EVENTS.filter(e=>e.kind==='inspection');assert.equal(es.length,8);assert.equal(EVENTS.length,12);assert.ok(es.every(e=>e.times.length===3&&new Set(e.times.map(String)).size===3));});
test('seven daily actions, salary at end only, rotating first player',()=>{const g=quiet(make()),m=g.players[0].money;for(let day=0;day<7;day++)for(let id=0;id<3;id++){assert.equal(g.day,day);assert.equal(E.activeBuyer(g),id);E.pass(g,id);}assert.equal(g.actionCount,21);assert.equal(g.players[0].money,m+14);E.resolveAll(g);assert.equal(g.players[0].money,m+14+6);assert.equal(g.players[0].sanity,3);next(g);assert.equal(E.activeBuyer(g),1);assert.equal(g.day,0);});
test('buy refills without placing, failed purchase atomic, locked advanced can be bought',()=>{const g=quiet(make({startMoney:99})),p=g.players[0],before=JSON.stringify(g);assert.throws(()=>E.buy(g,1,g.market[2][0].uid));assert.equal(JSON.stringify(g),before);const c=g.market[2][0];E.buy(g,0,c.uid);assert.equal(E.findPlacement(p,c.uid),null);assert.equal(g.market[2].length,5);turn(g);const big=g.decks[8].find(c=>getCard(c).requires);g.decks[8]=g.decks[8].filter(x=>x!==big);g.market[8].push(big);E.buy(g,0,big.uid);turn(g);assert.match(E.canPlace(g,p,big.uid,am),/技能/);});
test('refresh exhausted deck draws old discard before discarding current offer',()=>{const g=quiet(make()),c=g.market[2][0],other=g.decks[2][0],p=g.players[0],m=p.money;g.decks[2]=[];g.discard[2]=[other];E.refresh(g,0,c.uid);assert.ok(g.market[2].includes(other));assert.deepEqual(g.discard[2],[c]);assert.equal(p.money,m);assert.equal(p.sanity,3);});
test('past source and destination locked, failures atomic',()=>{const g=quiet(make()),p=g.players[0],c=p.cards[1];E.place(g,0,c.uid,{day:0,period:0});turn(g);const before=JSON.stringify(g);assert.throws(()=>E.place(g,0,c.uid,am),/过去/);assert.throws(()=>E.place(g,0,p.cards[0].uid,{day:0,period:0}),/今天/);assert.throws(()=>E.unplace(g,0,c.uid));assert.equal(JSON.stringify(g),before);});
test('2h uses the only daytime card slot; one 2h night has no night pressure',()=>{const g=quiet(make()),p=g.players[0];E.place(g,0,p.cards[2].uid,am);turn(g);assert.match(E.canPlace(g,p,p.cards[1].uid,am),/先用/);E.place(g,0,p.cards[1].uid,night);assert.equal(p.sanity,2);assert.equal(E.slotHours(p,night),2);});
test('8h anchors once, covers two halves, resolves once at PM, one placement action',()=>{const g=quiet(make({startSanity:4})),p=g.players[0],c=add(g,p,'market-service');E.place(g,0,c.uid,pm);assert.equal(g.actionCount,1);assert.equal(E.findPlacement(p,c.uid).key,'6-0');assert.deepEqual(E.cardsInSlot(p,am),[c]);assert.deepEqual(E.cardsInSlot(p,pm),[c]);assert.equal(E.slotHours(p,am),4);turn(g);for(const s of [am,pm])assert.match(E.canPlace(g,p,p.cards[2].uid,s),/先用/);finish(g);assert.equal(p.income,7);assert.equal(p.inspiration,2);assert.equal(g.history[0].steps,1);assert.equal(g.logs.filter(l=>l.tone==='income'&&l.slot).length,1);assert.equal(g.logs.find(l=>l.tone==='income'&&l.slot).slot.period,1);});
test('8h rejects occupied PM and night; failed placement atomic',()=>{const g=quiet(make({startSanity:4})),p=g.players[0],c=add(g,p,'market-service');E.place(g,0,p.cards[2].uid,pm);turn(g);const before=JSON.stringify(g);assert.throws(()=>E.place(g,0,c.uid,am),/先用/);assert.throws(()=>E.place(g,0,c.uid,night),/完整白天/);assert.equal(JSON.stringify(g),before);});
test('8h moving frees both old halves; stress and withdrawal charged once',()=>{const g=quiet(make({startSanity:4})),p=g.players[0],c=add(g,p,'market-service');E.place(g,0,c.uid,{day:3,period:0});turn(g);E.place(g,0,c.uid,pm);assert.equal(p.sanity,3);assert.equal(E.cardsInSlot(p,{day:3,period:1}).length,0);turn(g);E.unplace(g,0,c.uid);assert.equal(p.sanity,4);assert.equal(E.cardsInSlot(p,pm).length,0);});
test('team blocks either half, existing full-day activity pauses without cost',()=>{for(const s of [am,pm]){const g=quiet(make({startSanity:4})),p=g.players[0],c=add(g,p,'market-service');g.inspection.blockedTimes=[s];assert.match(E.canPlace(g,p,c.uid,am),/团建/);g.inspection.blockedTimes=[];E.place(g,0,c.uid,am);g.inspection.blockedTimes=[s];finish(g);assert.equal(p.inspiration,4);assert.equal(p.income,0);assert.ok(E.findPlacement(p,c.uid));}});
test('8h inspection of either half cancels whole activity; fine 4h or 8h once',()=>{for(const times of [[{day:0,period:0}],[{day:0,period:1}],[{day:0,period:0},{day:0,period:1}]]){const g=quiet(make({startSanity:10})),p=g.players[0],c=add(g,p,'market-service');g.inspection={name:'查岗',times,blockedTimes:[],money:1,sanity:1};E.place(g,0,c.uid,{day:0,period:0});const m=p.money;finish(g);assert.equal(p.income,0);assert.equal(p.inspiration,4);assert.equal(p.sanity,9-times.length*4);assert.equal(p.money,m+12+6-times.length*4);assert.equal(p.caught,1);}});
test('2h/4h inspection fines scale by hours; salary remains',()=>{for(const [type,h]of [['music',2],['reading',4]]){const g=quiet(make({startSanity:8})),p=g.players[0],c=add(g,p,type);g.inspection={name:'查岗',times:[{day:0,period:0}],blockedTimes:[],money:1,sanity:1};E.place(g,0,c.uid,{day:0,period:0});const m=p.money;finish(g);assert.equal(p.sanity,8-h);assert.equal(p.money,m+12+6-h);assert.equal(p.inspiration,4);}});
test('2+2h night occupies 4 sanity once, withdrawal releases it',()=>{const g=quiet(make({startSanity:8})),p=g.players[0],c=add(g,p,'podcast');E.place(g,0,p.cards[2].uid,night);assert.equal(p.sanity,8);turn(g);E.place(g,0,c.uid,night);assert.equal(p.sanity,4);turn(g);assert.match(E.canPlace(g,p,p.cards[1].uid,night),/4h/);finish(g);assert.equal(p.sanity,4);next(g);quiet(g);turn(g);E.unplace(g,0,c.uid);assert.equal(p.sanity,8);});
test('starting sanity cannot afford 4h night activity',()=>{const g=quiet(make());assert.match(E.canPlace(g,g.players[0],g.players[0].cards[0].uid,night),/低于 0/);});
test('life activity yields inspiration only; completing it releases night pressure',()=>{const g=quiet(make({startSanity:8})),p=g.players[0],c=p.cards[0];E.place(g,0,c.uid,night);assert.equal(p.sanity,4);finish(g);assert.equal(p.sanity,8);assert.equal(p.inspiration,8);assert.ok(!p.cards.includes(c));});
test('two one-shot life activities cannot manufacture sanity by releasing night pressure',()=>{const g=quiet(make({startSanity:8})),p=g.players[0],a=add(g,p,'spa'),b=add(g,p,'walk');E.place(g,0,a.uid,night);turn(g);E.place(g,0,b.uid,night);assert.equal(p.sanity,4);finish(g);assert.equal(p.sanity,8);assert.ok(g.discard[2].includes(a)&&g.discard[2].includes(b));});
test('life cards never raise sanity, including zero; defaults and range preserved',()=>{for(const initial of [0,3,10]){const g=quiet(make({startSanity:initial})),p=g.players[0],c=p.cards[0];E.place(g,0,c.uid,am);finish(g);assert.equal(p.sanity,initial);assert.ok(g.discard[4].includes(c));next(g);quiet(g);finish(g);assert.equal(p.sanity,initial);}assert.equal(make({startSanity:24}).players[0].sanity,10);});
test('moves and withdrawal cannot manufacture sanity at cap',()=>{const g=quiet(make({startSanity:10})),p=g.players[0],c=p.cards[1];E.place(g,0,c.uid,am);turn(g);E.place(g,0,c.uid,night);assert.equal(p.sanity,9);turn(g);E.unplace(g,0,c.uid);assert.equal(p.sanity,10);});
test('post-placement sanity gate atomic; later accountability pauses execution',()=>{const g=quiet(make({startSanity:1})),p=g.players[0],before=JSON.stringify(g);assert.throws(()=>E.place(g,0,p.cards[1].uid,am),/门槛/);assert.equal(JSON.stringify(g),before);g.config.startSanity=3;E.syncSanity(g,p);E.place(g,0,p.cards[1].uid,am);p.accountability=3;E.syncSanity(g,p);finish(g);assert.equal(p.income,0);assert.equal(p.inspiration,4);});
test('skills unique by type; duplicate growth enters duration discard',()=>{const g=quiet(make()),p=g.players[0],a=add(g,p,'journal'),b=add(g,p,'journal');E.place(g,0,a.uid,am);turn(g);E.place(g,0,b.uid,pm);finish(g);assert.equal(E.skillCounts(p).A,1);assert.ok(g.discard[2].includes(b));assert.equal(p.sanity,3);});
test('draft scans unrevealed shared 8h deck, preserves skipped order and returns other card',()=>{const g=quiet(make()),p=g.players[0];g.phase='escape';p.drafts=[{id:'t',pool:'A',options:null}];const before=[...g.decks[8]],market=[...g.market[8]];E.openDraft(g,0,'t');const draft=p.drafts[0];assert.ok(draft.options.every(c=>getCard(c).tier==='advanced'&&getCard(c).route==='A'));assert.deepEqual(g.decks[8],before.filter(c=>!draft.options.includes(c)));assert.deepEqual(g.market[8],market);const chosen=draft.options[0],rest=draft.options.slice(1);E.chooseAdvanced(g,0,'t',chosen.uid);assert.ok(p.cards.includes(chosen));assert.deepEqual(g.decks[8].slice(0,rest.length),rest);});
test('empty draft gives money, not sanity',()=>{const g=quiet(make()),p=g.players[0];g.phase='escape';p.drafts=[{id:'t',pool:'any',options:null}];g.decks[8]=g.decks[8].filter(c=>getCard(c).tier!=='advanced');const m=p.money;E.openDraft(g,0,'t');assert.equal(p.money,m+2);assert.equal(p.sanity,3);assert.equal(p.drafts.length,0);});
test('two-week core progresses once despite two occupied halves, active following week',()=>{const g=quiet(make({startMoney:50,startSanity:7})),p=g.players[0];skills(g,p,'AAAA');const c=add(g,p,'royalty');E.place(g,0,c.uid,am);finish(g);assert.equal(c.progress,1);assert.equal(p.inspiration,3);assert.equal(p.income,0);next(g);quiet(g);finish(g);assert.equal(c.progress,2);assert.equal(p.upgrades.length,1);assert.equal(p.sanity,7);assert.equal(p.income,0);assert.equal(E.cardsInSlot(p,pm).length,0);next(g);quiet(g);finish(g);assert.equal(p.income,6);});
test('muse boosts first A income only, no weekly sanity gain',()=>{const g=quiet(make({startSanity:6})),p=g.players[0];p.upgrades.push({uid:'core',type:'muse',activeFrom:1});const a=add(g,p,'proofread'),b=add(g,p,'tutoring');E.place(g,0,a.uid,am);turn(g);E.place(g,0,b.uid,pm);const sanity=p.sanity;finish(g);assert.equal(p.income,10);assert.equal(p.inspiration,3);assert.equal(p.sanity,sanity);});
test('A growth before income does not consume muse income power',()=>{const g=quiet(make({startSanity:6})),p=g.players[0];p.upgrades.push({uid:'core',type:'muse',activeFrom:1});const a=add(g,p,'journal'),b=add(g,p,'proofread');E.place(g,0,a.uid,am);turn(g);E.place(g,0,b.uid,pm);const sanity=p.sanity;finish(g);assert.equal(p.income,6);assert.equal(p.inspiration,5);assert.equal(p.sanity,sanity);});
test('weekend project 3/3 frees Saturday and both occupied halves',()=>{const g=quiet(make()),p=g.players[0],c=add(g,p,'weekend');E.place(g,0,p.cards[1].uid,{day:0,period:0});turn(g);E.place(g,0,c.uid,am);for(let week=1;week<=3;week++){if(week>1){next(g);quiet(g);p.inspiration++;}finish(g);assert.equal(c.progress,week);assert.equal(p.weekend,week===3);}assert.ok(p.completedProjects.includes(c));assert.equal(E.cardsInSlot(p,pm).length,0);assert.equal(E.workType(p,{day:5,period:0}),null);});
test('no progress when blocked, caught, gate unmet, no earlier income or no resources',()=>{for(const reason of ['team','caught','sanity','income','money']){const g=quiet(make()),p=g.players[0],c=add(g,p,'weekend');E.place(g,0,c.uid,am);while(g.phase==='planning')E.pass(g,E.activeBuyer(g));p.jobsDone=1;if(reason==='team')g.inspection.blockedTimes=[pm];if(reason==='caught'){p.schedule={'0-0':[c.uid]};g.timeline=[{day:0,period:1}];Object.assign(g.inspection,{times:[{day:0,period:0}],money:1,sanity:1});}if(reason==='sanity'){p.accountability=10;E.syncSanity(g,p);}if(reason==='income')p.jobsDone=0;if(reason==='money')p.money=0;E.resolveAll(g);assert.equal(c.progress,undefined,reason);assert.equal(p.weekend,false);}});
test('progress survives withdrawal, placement and save reload; discard clears it',()=>{let g=quiet(make()),p=g.players[0],c=add(g,p,'weekend');c.progress=1;E.place(g,0,c.uid,am);turn(g);E.unplace(g,0,c.uid);g=JSON.parse(JSON.stringify(g));p=g.players[0];c=E.cardAt(p,c.uid);turn(g);E.place(g,0,c.uid,pm);assert.equal(c.progress,1);turn(g);E.discardCard(g,0,c.uid);assert.equal(c.progress,undefined);assert.ok(g.discard[8].includes(c));assert.equal(p.weekend,false);});
test('preview neither mutates progress nor doubles full-day income',()=>{const g=quiet(make({startSanity:4})),p=g.players[0],c=add(g,p,'market-service');E.place(g,0,c.uid,am);const before=JSON.stringify(g);assert.equal(E.preview(g,0).income,7);assert.equal(JSON.stringify(g),before);});
test('strict >16 income, N-1 ends same week, no resource-score victory',()=>{const g=quiet(make());finish(g);g.players[0].income=16;assert.equal(E.eligible(g,g.players[0]),false);for(const p of g.players.slice(0,2)){p.income=17;delete g.escapeDecisions[p.id];E.chooseEscape(g,p.id);}g.players[2].money=9999;E.closeWeek(g);assert.equal(g.phase,'ended');assert.equal(g.week,1);assert.equal(E.won(g,g.players[2]),false);});
test('escaped ignores company events, still pays night pressure',()=>{const g=quiet(make({startSanity:8})),p=g.players[0];p.escaped=true;g.inspection.times=[am];g.inspection.blockedTimes=[pm];assert.equal(E.inspected(g,p,am),false);assert.equal(E.eventBlocksSlot(g,p,pm),false);E.place(g,0,p.cards[0].uid,night);assert.equal(p.sanity,6);});
test('fixed seed reproducible, duration metadata consistent',()=>{assert.deepEqual(make({seed:42}),make({seed:42}));assert.ok([...CARDS,...ADVANCED].every(d=>String(hours(d.size))===marketLane(d)));});
for(const playerCount of [2,3,4])test(`${playerCount} players: complete legal game, conservation, one daily action`,()=>{const g=E.createGame({playerCount,seed:42});g.players.forEach(p=>p.bot=true);const ids=allCards(g).map(c=>c.uid).sort();let guard=0;while(g.phase!=='ended'&&guard++<35){while(g.phase==='planning'){const before=g.actionCount;E.botAct(g);assert.equal(g.actionCount,before+1);for(const p of g.players)for(let day=0;day<7;day++)for(let period=0;period<3;period++){assert.ok(E.slotHours(p,{day,period})<=4);if(period!==2)assert.ok(E.cardsInSlot(p,{day,period}).length<=1);}}E.resolveAll(g);assert.equal(g.history.at(-1).actions,7*playerCount);for(const p of g.players){E.botDraft(g,p.id);if(!Object.hasOwn(g.escapeDecisions,p.id))E.chooseEscape(g,p.id);}E.closeWeek(g);assert.deepEqual(allCards(g).map(c=>c.uid).sort(),ids);for(const p of g.players)assert.ok(p.money>=0&&p.sanity>=0&&p.sanity<=10&&p.inspiration>=0);}assert.equal(g.phase,'ended');});
