import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import {CARDS,ADVANCED,PROJECTS,EVENTS,MARKET_LIMITS,getCard} from '../src/cards.js';
import {make,turn,lock,finish,next,add,skills,rig,seedFor} from './helpers.mjs';
const am={day:6,period:0},pm={day:6,period:1},night={day:6,period:2};
test('v10 pool, economy and no sanity resource fields',()=>{const g=make();assert.equal(g.version,12);assert.equal(CARDS.length,40);assert.equal(ADVANCED.length,16);assert.equal(PROJECTS.length,2);assert.equal(g.config.salary,2);assert.equal(g.config.livingCost,undefined);assert.equal(g.config.escapeIncome,10);for(const [lane,n]of Object.entries(MARKET_LIMITS))assert.equal(g.market[lane].length,n);for(const d of [...CARDS,...ADVANCED,...PROJECTS])for(const field of ['price','cost','gain'])assert.ok(!Object.hasOwn(d[field],'sanity'),d.id);});
test('eight of twelve events announce only 1–3 checks',()=>{assert.equal(EVENTS.length,12);assert.deepEqual([1,2,3].map(n=>EVENTS.filter(e=>e.inspectionCount===n).length),[4,3,1]);assert.ok(EVENTS.every(e=>!e.times));});
test('seven alternating actions and salary exactly two, no expenses',()=>{const g=make(),m=g.players[0].money;for(let d=0;d<7;d++)for(let id=0;id<2;id++){assert.equal(g.day,d);assert.equal(E.activeBuyer(g),id);E.pass(g,id);}assert.equal(g.players[0].money,m+7);E.resolveAll(g);assert.equal(g.players[0].money,m+9);next(g);assert.equal(E.activeBuyer(g),1);});
test('buy refills immediately, does not place, invalid turn atomic',()=>{const g=make(),p=g.players[0],c=g.market[2][0],before=JSON.stringify(g);assert.throws(()=>E.buy(g,1,c.uid));assert.equal(JSON.stringify(g),before);E.buy(g,0,c.uid);assert.ok(p.cards.includes(c));assert.equal(E.findPlacement(p,c.uid),null);assert.equal(g.market[2].length,5);});
test('locked advanced can be bought but not scheduled',()=>{const g=make({startMoney:30}),p=g.players[0],c=g.decks[8].find(c=>getCard(c).requires);g.decks[8]=g.decks[8].filter(x=>x!==c);g.market[8].push(c);E.buy(g,0,c.uid);turn(g);assert.match(E.canPlace(g,p,c.uid,am),/技能/);});
test('整备只拿钱，不破坏公共市场',()=>{const g=make(),before=structuredClone(g.market),money=g.players[0].money;E.pass(g,0);assert.deepEqual(g.market,before);assert.equal(g.players[0].money,money+1);assert.equal(E.refresh,undefined);});
test('past source and destination cannot move and failures atomic',()=>{const g=make(),p=g.players[0],c=p.cards[1];E.place(g,0,c.uid,{day:0,period:0});turn(g);const before=JSON.stringify(g);assert.throws(()=>E.place(g,0,c.uid,am),/过去/);assert.throws(()=>E.unplace(g,0,c.uid));assert.throws(()=>E.place(g,0,p.cards[2].uid,{day:0,period:0}),/今天/);assert.equal(JSON.stringify(g),before);});
test('8h occupies both halves, executes once and cannot overlap another card',()=>{const g=make(),p=g.players[0],c=add(g,p,'A08');E.place(g,0,c.uid,pm);assert.equal(E.findPlacement(p,c.uid).key,'6-0');assert.deepEqual(E.cardsInSlot(p,am),[c]);assert.deepEqual(E.cardsInSlot(p,pm),[c]);turn(g);assert.match(E.canPlace(g,p,p.cards[2].uid,pm),/先用/);finish(g);assert.equal(p.income,3);assert.equal(p.inspiration,2);assert.equal(g.history[0].steps,1);});
test('8h rejects night; moving and withdrawal release both halves',()=>{const g=make(),p=g.players[0],c=add(g,p,'A08');assert.match(E.canPlace(g,p,c.uid,night),/完整白天/);E.place(g,0,c.uid,{day:4,period:0});turn(g);E.place(g,0,c.uid,pm);assert.equal(E.cardsInSlot(p,{day:4,period:1}).length,0);turn(g);E.unplace(g,0,c.uid);assert.equal(p.sanity,3);});
test('team pauses existing 8h card on either half with no consumption',()=>{for(const s of [am,pm]){const g=make(),p=g.players[0],c=add(g,p,'A08');g.inspection.blockedTimes=[s];assert.match(E.canPlace(g,p,c.uid,am),/团建/);g.inspection.blockedTimes=[];E.place(g,0,c.uid,am);g.inspection.blockedTimes=[s];finish(g);assert.equal(p.income,0);assert.equal(p.inspiration,4);assert.ok(E.findPlacement(p,c.uid));}});
test('inspection hidden until lock, shared and repeated days not rerolled',()=>{const g=make();g.inspection.inspectionCount=3;g.diceRandom=seedFor([2,2,5]);assert.throws(()=>E.rollInspections(g),/确定后/);lock(g);assert.deepEqual(g.inspection.times,[]);E.step(g);assert.deepEqual(g.inspection.rolls,[2,2,5]);assert.deepEqual(g.inspection.times,[{day:1,period:0},{day:1,period:1},{day:4,period:0},{day:4,period:1}]);const rng=g.diceRandom;E.rollInspections(g);assert.equal(g.diceRandom,rng);assert.equal(g.diceRolls.length,1);});
test('2/4/8h each fined exactly one, whole activity paused once, sanity unaffected',()=>{for(const type of ['A05','A07','A08']){const g=make(),p=g.players[0],c=add(g,p,type);g.inspection.inspectionCount=3;g.diceRandom=seedFor([1,1,1]);E.place(g,0,c.uid,{day:0,period:0});lock(g);const money=p.money,sanity=p.sanity;E.resolveAll(g);assert.equal(p.money,money+2-1);assert.equal(p.inspiration,4);assert.equal(p.income,0);assert.equal(p.sanity,sanity);assert.equal(p.caught,1);assert.equal(g.diceRolls.filter(x=>x.kind==='activity').length,0);}});
test('shared inspection hits both players, never Sunday or nights',()=>{const g=make();g.inspection.inspectionCount=1;g.diceRandom=seedFor([1]);for(const p of g.players)rig(g,p,[['A05',0,0],['A05',0,2],['A05',6,0]]);finish(g);for(const p of g.players){assert.equal(p.caught,1);assert.equal(p.inspiration,6);}});
test('professional work immune, restricted to work hours, salary not side income',()=>{const g=make(),p=g.players[0],c=add(g,p,'W05');assert.match(E.canPlace(g,p,c.uid,am),/履职/);E.place(g,0,c.uid,{day:0,period:0});g.inspection.inspectionCount=1;g.diceRandom=seedFor([1]);lock(g);const money=p.money;E.resolveAll(g);assert.equal(p.caught,0);assert.equal(p.money,money+3);assert.equal(p.income,0);});
test('professional work pauses on temporary holiday',()=>{const g=make(),p=g.players[0];rig(g,p,[['W05',5]]);p.tempWeekend=true;lock(g);const money=p.money;E.resolveAll(g);assert.equal(p.money,money+2);});
for(const [id,resource,values,fixed]of [['W06','salary',[0,0,0,2,2,4],0],['A07','profit',[0,0,2,2,4,4],0],['C06','profit',[0,0,1,1,2,2],1]])test(`${id}: all six faces, pay before roll, salary excluded from escape`,()=>{for(let face=1;face<=6;face++){const g=make(),p=g.players[0];rig(g,p,[[id,id==='W06'?0:6]]);g.diceRandom=seedFor([face]);lock(g);const m=p.money;E.resolveAll(g);assert.equal(p.money,m+2+values[face-1]+fixed);assert.equal(p.income,resource==='salary'?0:values[face-1]+fixed);assert.equal(p.inspiration,id==='A07'?3:4);assert.equal(g.diceRolls.filter(r=>r.kind==='activity').length,1);assert.equal(g.diceRolls.at(-1).face,face);}});
test('unaffordable dice activity consumes neither resources nor roll',()=>{const g=make({startInspiration:0}),p=g.players[0];rig(g,p,[['A07',6]]);const rng=g.diceRandom;finish(g);assert.equal(g.diceRandom,rng);assert.equal(p.income,0);});
test('preview independent of hidden seed, does not mutate or consume RNG',()=>{const g=make(),p=g.players[0];rig(g,p,[['A07',6]]);g.inspection.inspectionCount=3;const original=JSON.stringify(g),preview=E.preview(g,0);assert.equal(JSON.stringify(g),original);assert.equal(preview.incomeLow,0);assert.equal(preview.incomeHigh,4);g.diceRandom=seedFor([6]);assert.deepEqual(E.preview(g,0),preview);});
test('reload after roll retains result; step vs resolveAll identical',()=>{const g=make();g.inspection.inspectionCount=2;rig(g,g.players[0],[['A07',6]]);lock(g);E.step(g);const a=structuredClone(g),b=JSON.parse(JSON.stringify(g));E.resolveAll(a);while(b.phase==='resolving')E.step(b);assert.deepEqual(a,b);assert.equal(a.diceRolls.filter(x=>x.kind==='inspection').length,1);});
test('capital locks once, moving retains, withdrawal returns without income',()=>{const g=make(),p=g.players[0],c=add(g,p,'C06'),m=p.money;E.place(g,0,c.uid,{day:4,period:0});assert.equal(p.money,m-3);turn(g);E.place(g,0,c.uid,am);assert.equal(p.money,m-3);turn(g);E.unplace(g,0,c.uid);assert.equal(p.money,m);assert.equal(p.income,0);assert.equal(c.lockedCapital,undefined);});
test('capital cannot be arranged without funds, failed operation atomic',()=>{const g=make({startMoney:2}),p=g.players[0],c=add(g,p,'C06'),before=JSON.stringify(g);assert.throws(()=>E.place(g,0,c.uid,am),/本金/);assert.equal(JSON.stringify(g),before);});
test('unique growth archives; duplicate discarded; W never substitutes for A',()=>{const g=make(),p=g.players[0];rig(g,p,[['A02',6,0],['A02',6,1]]);finish(g);assert.equal(E.skillCounts(p).A,1);assert.equal(g.discard[2].length,1);skills(p,'WWWW');assert.deepEqual(E.skillMissing(p,getCard('A09')),['A','A','A']);});
test('search takes only unseen matching advanced, unchosen goes to bottom',()=>{const g=make(),p=g.players[0];g.phase='escape';p.drafts=[{id:'d',pool:'A',options:null}];const before=[...g.decks[8]],market=[...g.market[8]];E.openDraft(g,0,'d');const d=p.drafts[0];assert.equal(d.options.length,2);assert.ok(d.options.every(c=>getCard(c).tier==='advanced'&&getCard(c).route==='A'));assert.deepEqual(g.decks[8],before.filter(c=>!d.options.includes(c)));assert.deepEqual(g.market[8],market);const [a,b]=d.options;E.chooseAdvanced(g,0,'d',a.uid);assert.ok(p.cards.includes(a));assert.equal(g.decks[8][0],b);});
test('empty search gives one money, no sanity',()=>{const g=make(),p=g.players[0];g.phase='escape';g.decks[8]=[];p.drafts=[{id:'d',pool:'any',options:null}];E.openDraft(g,0,'d');assert.equal(p.money,9);assert.equal(p.sanity,3);assert.equal(p.drafts.length,0);});
test('next activity boost consumed by failed or non-income activity',()=>{for(const middle of ['A05','A07']){const g=make({startInspiration:0}),p=g.players[0];rig(g,p,[['B07',4], [middle,5],['C05',6]]);finish(g);assert.equal(p.income,middle==='A05'?1:0);}});
test('green doubles only fixed portion; no doubling of pure dice income',()=>{for(const [target,expected]of [['C06',3],['A07',2]]){const g=make(),p=g.players[0];skills(p,'BBB');rig(g,p,[['B09',4],[target,6]]);g.diceRandom=seedFor([4]);finish(g);assert.equal(p.income,expected);}});
test('project requires credit and separate arranging action; progresses once/week',()=>{const g=make({startMoney:30}),p=g.players[0],project=p.projects[0];assert.throws(()=>E.buyProject(g,0,project.uid),/信用/);skills(p,'WW');E.buyProject(g,0,project.uid);assert.equal(E.findPlacement(p,project.uid),null);turn(g);E.place(g,0,project.uid,{day:5,period:0});turn(g);E.place(g,0,p.cards.find(c=>c.type==='C05').uid,{day:4,period:0});for(let week=1;week<=3;week++){if(week>1)next(g);finish(g);assert.equal(project.progress,week);assert.equal(p.weekend,week===3);}assert.ok(p.completedProjects.includes(project));assert.equal(E.cardsInSlot(p,{day:5,period:1}).length,0);assert.equal(E.workType(p,{day:5,period:0}),null);});
test('project does not progress without earlier side work',()=>{const g=make(),p=g.players[0];skills(p,'WW');rig(g,p,[['P01',5]]);finish(g);assert.equal(p.cards[0].progress,undefined);});
test('elastic protection starts next week; chosen once before first action; 2h only',()=>{const g=make(),p=g.players[0];skills(p,'WWW');rig(g,p,[['P02',0]]);finish(g);assert.equal(p.protectionFrom,2);next(g);turn(g);E.setProtection(g,0,{day:0,period:0});assert.throws(()=>E.setProtection(g,0,{day:1,period:0}));rig(g,p,[['A05',0],['A07',0,1]]);g.inspection.inspectionCount=1;g.diceRandom=seedFor([1]);finish(g);assert.equal(p.caught,1);assert.equal(p.inspiration,5);});
test('income ten and sanity six qualify; N−1 ends same week',()=>{const g=make({startSanity:6}),p=g.players[0];g.phase='escape';p.income=9;assert.equal(E.eligible(g,p),false);p.income=10;assert.equal(E.eligible(g,p),true);g.escapeDecisions={1:false};E.chooseEscape(g,0);E.closeWeek(g);assert.equal(g.phase,'ended');assert.equal(p.escaped,true);assert.equal(g.week,1);});
test('income track caps ten but money receives all profits',()=>{const g=make({startSanity:10,startInspiration:20}),p=g.players[0];rig(g,p,[['A08',0],['A08',1],['A08',2],['A08',6]]);lock(g);const m=p.money;E.resolveAll(g);assert.equal(p.rawIncome,12);assert.equal(p.income,10);assert.equal(p.money,m+14);});
for(const [name,pattern,plan,low,high]of [
 ['creative','AAAA',[['A06',0],['A05',0,2],['A05',1,2],['A09',2],['A08',4],['A10',6]],10,10],
 ['developer','BBBB',[['B05',0,2],['B05',1,2],['B05',2,2],['B09',3],['B06',4],['B10',5],['B08',6]],10,10],
 ['business','CCCC',[['C09',1],['C08',3],['C10',6]],10,10],
 ['creative-commercial','AACC',[['A06',0],['C11',1],['A12',3],['C08',6]],10,10],
 ['developer-commercial','BCCC',[['B12',0],['C06',1],['C09',3],['C08',6]],8,10],
 ['career-transition','WWABCC',[['W05',0],['A05',0,2],['A05',1,2],['A05',2,2],['W11',3],['W12',4],['C12',6]],10,10],
])test(`prepared ${name} engine matches documented income`,()=>{const g=make({startMoney:50}),p=g.players[0];skills(p,pattern);rig(g,p,plan);const preview=E.preview(g,0);assert.equal(preview.incomeLow,low);assert.equal(preview.incomeHigh,high);g.diceRandom=seedFor([6]);finish(g);assert.equal(p.income,high);});
