import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../src/engine.js';
import {make,turn,finish,next,add,skills,rig} from './helpers.mjs';
const night={day:6,period:2};
test('skills never increase sanity; permanent weekend and escape do not stack',()=>{const g=make(),p=g.players[0];skills(p,'WWWWAAAABBBBCCCC');assert.equal(E.syncSanity(g,p),3);p.tempWeekend=true;assert.equal(E.syncSanity(g,p),3);p.weekend=true;assert.equal(E.syncSanity(g,p),5);p.escaped=true;assert.equal(E.syncSanity(g,p),7);});
test('pressure and withdrawal never manufacture sanity at upper cap',()=>{const g=make({startSanity:10}),p=g.players[0],c=add(g,p,'C05');p.weekend=true;E.place(g,0,c.uid,{day:6,period:0});assert.equal(p.sanity,9);turn(g);E.unplace(g,0,c.uid);assert.equal(p.sanity,10);});
test('4h night unaffordable from default three; 2+2 applies pressure once',()=>{const g=make(),p=g.players[0],c=add(g,p,'B07');assert.match(E.canPlace(g,p,c.uid,night),/低于 0/);g.config.startSanity=8;const repeat=add(g,p,'A05'),once=add(g,p,'A02');E.place(g,0,repeat.uid,night);turn(g);E.place(g,0,once.uid,night);assert.equal(p.sanity,4);finish(g);assert.equal(p.sanity,8);assert.equal(E.slotHours(p,night),2);});
test('failed minimum and maximum gates leave schedule and money unchanged',()=>{const g=make({startSanity:1}),p=g.players[0],c=add(g,p,'C05'),before=JSON.stringify(g);assert.throws(()=>E.place(g,0,c.uid,{day:6,period:0}),/门槛/);assert.equal(JSON.stringify(g),before);g.config.startSanity=5;const w=add(g,p,'W05');assert.match(E.canPlace(g,p,w.uid,{day:1,period:0}),/≤2/);});
test('no drift or weekly sanity recovery over five weeks',()=>{const g=make(),p=g.players[0];rig(g,p,[['A05',0,2],['C05',6]]);for(let i=0;i<5;i++){finish(g);assert.equal(p.sanity,2);assert.equal(p.income,1);if(i<4)next(g);}});
test('sanity recalculates from circumstances; no accountability field',()=>{const g=make(),p=g.players[0];assert.equal(p.accountability,undefined);assert.equal(g.config.inspectionAccountability,undefined);p.sanity=24;assert.equal(E.syncSanity(g,p),3);assert.equal(E.createGame({startSanity:24}).players[0].sanity,10);});
