import { DAYS, DEFAULTS, ROUTES, CARDS, ADVANCED, MARKET_LIMITS, STARTERS, getCard, slotKey, slotLabel } from './cards.js';
import * as E from './engine.js';
import { FAMILIES, familyOf, hours, specialRules } from './card-visuals.js';
import { icon } from './icons.js';
import { cardFace as face, iconHelp } from './card-face.js';
const STORAGE='escape-velocity-game-v9', app=document.querySelector('#app');
let game;try{const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved?.version===9&&saved.sanityModel==='circumstances-v1'&&saved.progressModel===1)game=saved;}catch{}
game ||= E.createGame();
// Recompute loaded bars too: completed skills no longer improve sanity.
for(const p of game.players) E.syncSanity(game,p);
let playerId=game.phase==='planning'?E.activeBuyer(game):0, selected=null, selectedSlot=null, shelf='hand', dialog=null, detail=null, botTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const resourceNames={money:'资金',sanity:'理智',inspiration:'灵感'};
const colors=['#42786b','#aa7650','#7766a0','#667f9b'];
const phaseNames={planning:'日程阶段',resolving:'结算阶段',escape:'周末复盘',ended:'终局'};
const current=()=>game.players[playerId];
const editable=p=>game.phase==='planning'&&E.activeBuyer(game)===p.id&&!p.bot;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(game));}catch{}}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),3500);}
function tokens(values={},sign='+'){return Object.entries(values).filter(([,n])=>n).map(([key,n])=>`<span class="effect-token ${key}" title="${resourceNames[key]} ${sign}${n}">${icon(key,14)}<b>${sign}${n}</b></span>`).join('');}
function skillSymbols(pattern){return [...pattern].map(r=>`<span class="skill-symbol family-${ROUTES[r].family}" title="${ROUTES[r].name}">${icon(ROUTES[r].icon,12)}${r}</span>`).join('');}
function cardTile(c,context,p){const d=getCard(c),where=context==='hand'?E.findPlacement(p,c.uid):null,can=editable(p),available=context==='market'?can&&E.canPay(p,d.price):can&&E.qualified(p,d)&&(!where||where.day>=game.day);
 return `<article class="game-card family-${familyOf(d)} ${selected===c.uid?'card-selected':''}" data-hours="${hours(d.size)}" style="--card-hours:${hours(d.size)}"><div class="card-paper">${face(d,false,c)}</div><div class="card-bottom"><button class="detail-button" data-action="detail" data-type="${d.id}" aria-label="${esc(d.name)}详情">${icon('info',15)}</button>${context==='market'?`<button data-action="buy" data-uid="${c.uid}" ${available?'':'disabled'}>购买</button><button data-action="refresh" data-uid="${c.uid}" ${can?'':'disabled'} title="用一次行动刷新这张牌" aria-label="刷新${esc(d.name)}">${icon('repeat',14)}</button>`:`<button data-action="select" data-uid="${c.uid}" ${available?'':'disabled'}>${selected===c.uid?'已选':where?'移动':E.qualified(p,d)?'安排':'缺技能'}</button>${where?`<button data-action="unplace" data-uid="${c.uid}" ${can&&where.day>=game.day?'':'disabled'} title="用一次行动撤回">${icon('undo',14)}</button>`:''}`}</div>${where?`<small class="card-location">${slotLabel(where)}</small>`:''}</article>`;
}
function slotTile(p,s){const list=E.cardsInSlot(p,s),full=list.some(c=>hours(getCard(c).size)===8),h=full?8:E.slotHours(p,s),work=E.workType(p,s),past=game.phase==='planning'&&s.day<game.day,blocked=(full?E.coveredSlots(getCard(list[0]),s):[s]).some(t=>E.eventBlocksSlot(game,p,t)),caught=(full?E.coveredSlots(getCard(list[0]),s):[s]).some(t=>E.inspected(game,p,t)),allowed=selected&&editable(p)&&!E.canPlace(game,p,selected,s),chosen=selectedSlot&&slotKey(selectedSlot)===slotKey(s),isNight=s.period===2;
 return `<div class="slot-track ${isNight?'night-track':''} ${full?'full-day-track':''}" style="--slot-hours:${full?8:4}"><span class="slot-caption">${icon(isNight?'moon':'sun',12)} ${full?'上午—下午':['上午','下午','夜晚'][s.period]}<b>${h||0}/${full?8:4}h</b></span><div class="physical-well ${caught?'inspected':''} ${allowed?'placeable':''} ${chosen?'selected-slot':''} ${past?'past-slot':''} ${blocked?'blocked-slot':''}"><button class="slot v7-slot ${isNight?'night-slot':''}" data-action="slot" data-day="${s.day}" data-period="${s.period}" aria-label="${full?DAYS[s.day]+'全天':slotLabel(s)}${caught?'，公开查岗':''}${blocked?'，团建占用':''}" ${past?'disabled':''}>${list.length?list.map(c=>face(getCard(c),true,c)).join(''):`<div class="${isNight?'night-rest-content':work?'work-content':'free-content'}">${icon(isNight?'moon':work||'leaf',28)}<strong>${isNight?'休息':work==='meeting'?'开会':work?'坐班':'自由时光'}</strong><small>${isNight?'≤2h 不扣理智':work?'可直接安排摸鱼':'可安排一张活动'}</small></div>`}</button>${caught?`<span class="slot-badge danger">${icon('eye',12)} 查岗 · 每 h −${game.inspection.money}元 / ${game.inspection.sanity}问责</span>`:blocked?'<span class="slot-badge danger">团建 · 本周暂停</span>':isNight&&h>2?`<span class="slot-badge danger">熬夜压力 ${E.nightStress(game,h)}</span>`:h&&work?`<span class="slot-badge">摸鱼 ${h}h · 工资不变</span>`:''}</div></div>`;
}
function resources(p){return `<div class="resources">${[['money',p.money,'资金'],['sanity',p.sanity,'理智'],['inspiration',p.inspiration,'灵感'],['bag',p.income,'本周副业']].map(([k,n,label])=>`<div class="resource"><span class="resource-icon ${k}">${icon(k,22)}</span><div><span>${label}</span><strong>${n}</strong></div></div>`).join('')}</div><div class="sanity-track" aria-label="理智指标 ${p.sanity}，范围 0 到 10"><span>${icon('sanity',16)} 理智</span><div class="sanity-scale" style="--sanity-fill:${p.sanity*10}%">${Array.from({length:11},(_,n)=>`<span class="sanity-tick ${n===p.sanity?'current':''}" ${n===p.sanity?'aria-current="true"':''}>${n}</span>`).join('')}</div><small>≥ 门槛 · 处境决定状态</small></div><p class="sanity-explanation">起点 ${game.config.startSanity} · 自主 ${E.sanityState(game,p).freedom} · 日程压力 ${E.sanityState(game,p).pressure} · 当周问责 ${E.sanityState(game,p).accountability}</p>`;}
function board(p){const counts=E.skillCounts(p);return `<section class="calendar-panel"><div class="panel-heading"><div><span class="section-kicker">PERSONAL PLAYER BOARD</span><h2>${esc(p.name)}的工位之外</h2></div><span class="subtle">${p.escaped?'已逃离':p.weekend?'永久双休':p.tempWeekend?'本周双休':'周一至周六工作'}</span></div>${resources(p)}<div class="calendar-scroll"><div class="calendar-grid">${DAYS.map((day,i)=>`<div class="day-lane ${!E.workType(p,{day:i,period:0})?'free-day':''} ${game.phase==='planning'&&i===game.day?'current-day':''}"><div class="day-heading"><span class="day-number">${i+1}</span><strong>${day}</strong>${game.phase==='planning'&&i<game.day?icon('lock',12):''}</div>${[0,1,2].map(period=>period===1&&E.cardsInSlot(p,{day:i,period:0}).some(c=>hours(getCard(c).size)===8)?'':slotTile(p,{day:i,period})).join('')}</div>`).join('')}</div></div><div class="calendar-footer">2h / 4h 占半天一格 · 8h 连占上午与下午，下午结算一次 · 夜晚最多 4h</div><section class="skill-tray">${Object.entries(ROUTES).map(([r,info])=>`<details class="skill-stack family-${info.family}"><summary>${icon(info.icon,20)} ${info.name} <b>${counts[r]}</b></summary>${p.skills.filter(c=>getCard(c).skill===r).map(c=>`<span class="skill-slip">${getCard(c).name}</span>`).join('')||'<small>完成一次性活动留下经历</small>'}</details>`).join('')}</section>${p.upgrades.length?`<div class="upgrades-tray">${p.upgrades.map(c=>`<button class="upgrade-plaque family-${familyOf(getCard(c))}" data-action="detail" data-type="${c.type}">${icon('achievement',20)}${getCard(c).name} · ${c.activeFrom>game.week?'下周生效':'已生效'}</button>`).join('')}</div>`:''}</section>`;}
function editor(p){if(!selectedSlot)return '';const s=selectedSlot,cards=E.cardsInSlot(p,s);return `<section class="slot-editor"><h3>${slotLabel(s)}</h3>${cards.map(c=>`<div class="edit-row"><button data-action="detail" data-type="${c.type}">${esc(getCard(c).name)}</button><button data-action="select" data-uid="${c.uid}" ${editable(p)&&s.day>=game.day?'':'disabled'}>移动</button><button data-action="unplace" data-uid="${c.uid}" ${editable(p)&&s.day>=game.day?'':'disabled'}>撤回</button></div>`).join('')||'<p>从手牌选一张，再点此时段安排。</p>'}<small>移动、撤回各花一次行动。替换需要先撤回，再安排。</small></section>`;}
function sidebar(p){const prediction=game.phase==='planning'?E.preview(game,p.id):null;return `<aside class="sidebar"><section class="phase-card"><span class="section-kicker">WEEK ${game.week}</span><h3>${phaseNames[game.phase]}</h3>${game.phase==='planning'?`<p><b>${DAYS[game.day]} · ${esc(game.players[E.activeBuyer(game)].name)}</b>行动</p><p>① 买一张牌<br>② 安排 / 移动 / 撤回一张<br>③ 整备：拿钱或刷新一张</p><button class="primary-button" data-action="pass" ${editable(p)?'':'disabled'}>整备 · ${icon('money',16)} +${game.config.restMoney}</button><small>不计副业收入；刷新按钮在市场牌下。</small>`:game.phase==='resolving'?`<p>只结算自定义日程 ${game.cursor}/${game.timeline.length}</p><button class="primary-button" data-action="resolve">一键结算</button><button class="outline-button" data-action="step">下一时段</button>`:`<button class="primary-button" data-action="summary">${game.phase==='ended'?'查看终局':'周末结算'}</button>`}</section><section class="inspection-card"><span class="section-kicker">本周公开事件</span><h3>${icon('eye',20)} ${esc(game.inspection.name)}</h3><p>${esc(game.inspection.text)}</p>${game.inspection.times.length?`<p class="danger-text">${game.inspection.times.map(slotLabel).join('、')}<br>每摸鱼 1h：−${game.inspection.money} 资金 / ${game.inspection.sanity} 当周问责</p>`:''}</section><section class="escape-card"><h3>逃离门槛 &gt; ${game.config.escapeIncome}</h3><strong class="projected-income">${prediction?prediction.income:p.income}</strong><p>${prediction?'按当前日程与公开事件预计副业':'本周已结算副业'}</p>${prediction?.warnings.length?`<p class="danger-text">${prediction.warnings.length} 项可能失败</p><details><summary>查看原因</summary>${prediction.warnings.map(l=>`<p>${esc(l.text)}</p>`).join('')}</details>`:''}<small>工资、整备资金、奖金和非副业活动不计门槛。</small></section>${editor(p)}</aside>`;}
function shelfPanel(p){return `<section class="shelf-panel" id="shelf"><div class="shelf-header"><div class="shelf-tabs">${[['hand','我的卡牌'],['market','公共市场'],['log','本周记录']].map(([id,name])=>`<button data-action="shelf" data-tab="${id}" class="${shelf===id?'active':''}">${name}</button>`).join('')}</div><span class="shelf-hint">${shelf==='market'?'2h ×5 · 4h ×4 · 8h ×3 · 买后立即补位':'图标说明见玩家帮助 · 悬停可查看含义'}</span></div>${shelf==='hand'?`<p class="hand-hint">选择卡牌，再点击绿色时段。手牌 ${E.unplacedCards(p).length} 张；已安排牌也显示在这里，便于移动。</p><div class="hand-grid">${p.cards.map(c=>cardTile(c,'hand',p)).join('')}</div>`:shelf==='market'?`<div class="market-groups">${Object.entries(MARKET_LIMITS).map(([h,n])=>`<section class="duration-market"><div class="market-label"><span>${h}h 活动</span><small>${n} 展示位 · 牌堆 ${game.decks[h].length} · 弃牌 ${game.discard[h].length}</small></div><div class="market-grid">${game.market[h].map(c=>cardTile(c,'market',p)).join('')}</div></section>`).join('')}</div>`:`<div class="log-panel"><div class="log-list">${game.logs.filter(l=>l.week===game.week).slice().reverse().map(l=>`<div class="log-row"><span class="log-dot ${l.tone}"></span><strong>${l.player===null?'全体':esc(game.players[l.player].name)}</strong><p>${esc(l.text)}</p></div>`).join('')}</div><div class="notes-panel"><h3>测试笔记</h3><textarea id="notes" placeholder="记录卡手、策略与节奏…">${esc(game.notes||'')}</textarea><button data-action="export">导出整局记录</button></div></div>`}</section>`;}
function rules(){return `<div class="rules-grid">${[
 ['一天一次行动','周一至周日，按座次每人各做一次行动，再进入下一天。买牌、操作一个日程、整备三选一。每周起始玩家轮换。'],
 ['日期只往前走','周一可安排全周，周二只能安排周二及以后。移动时，出发和目标日期都必须尚未过去。买牌不自动安排，替换要先撤回再安排。'],
 ['摸鱼与熬夜','工作格无需解锁，半天每格放一张 2h 或 4h 活动，剩余时间不能另塞牌。8h 同时占上午与下午，一次行动安排、下午结算一次。任一半天被查岗，整项活动暂停，按被查半天实际占用的小时处罚；两个半天都被查则共罚 8h。夜晚最多两张 2h 或一张 4h。'],
 ['理智是状态指标',`开局 3，范围 0–10。技能积累不影响理智。起点加上自主状态（永久双休 2，逃离后改为 4），最多 10；再减日程压力和当周问责。没有任何卡牌直接获得或支付理智。安排后及执行前检查 ≥ 门槛。夜晚 2h 无额外压力，4h 占用 ${game.config.nightStress4}。撤回只解除相应压力；跨周不重复扣。问责本周累计，下一周清零，资金罚款不返还。降到 0 不淘汰，可以撤回日程。临时双休不改变长期状态。`],
 ['三个牌堆','仅 2h / 4h / 8h 三堆，亮 5 / 4 / 3 张。基础、生活、成长和高级混在对应时长牌堆。高级全部 8h，可先买后补技能。每种高级 1 张，普通每种每人 1 张；起始牌另发。争取双休在 8h 市场购买。手牌暂不限量。'],
 ['多周一次性','卡面的圆点是进度位。每次成功执行支付推进消耗、放一个指示物，每周最多一次；满格才获得完成奖励并离开日程。移动或撤回保留进度，抓包、团建、门槛或资源不足均不推进。争取双休 3 格，出版合约、自动化工作室、自己的小店各 2 格；永久核心完成后下周生效。'],
 ['技能与寻访','一次性成长成功后移入技能区，同名只计一次；技能不消耗。研讨会从未亮出的 8h 堆找对应路线高级牌，猎头找任意路线，抽二选一，未选放底。无候选补偿整备资金。'],
 ['周结与逃离',`日程阶段结束，按周一上午至周日夜晚结算已安排牌。然后工资 ${game.config.salary}，生活费 ${game.config.livingCost}，奖金；缺款形成等额当周问责。不再按工作日扣理智。副业收入 >${game.config.escapeIncome} 可逃离。N−1 人逃离后当周结束，无额外一周；未逃离称「究极牛马」。`],
 ['整备','拿 2 资金，或刷新一张市场明牌；均花一次行动。不能回复理智。生活活动提供灵感，不恢复理智；常驻灵感牌支持低收入循环；默认休息没有每周收益。']
 ].map(([title,text])=>`<article><h3>${title}</h3><p>${text}</p></article>`).join('')}</div>`;}
function settings(){const fields={startMoney:'起始资金',startSanity:'起始理智',startInspiration:'起始灵感',salary:'周薪',livingCost:'生活费',restMoney:'整备资金',nightStress4:'4h 熬夜影响',escapeIncome:'逃离收入门槛（需大于）',seed:'随机种子'};return `<p>v0.9 槽位压缩预设：2/4/8h；上下午各 4h，8h 占整个白天。理智按处境重算，彻底取消恢复牌；生活活动供应灵感，技能仅用于解锁，永久双休改善长期状态。旧存档单独保留。</p><form id="settings-form"><div class="setup-row"><label>人数<select name="playerCount">${[2,3,4].map(n=>`<option ${n===game.config.playerCount?'selected':''}>${n}</option>`).join('')}</select></label><label>方式<select name="mode"><option value="bots" ${game.config.mode==='bots'?'selected':''}>你 + 自动玩家</option><option value="hotseat" ${game.config.mode==='hotseat'?'selected':''}>同机轮流</option></select></label></div><label>起始生活牌<select name="starterActivity">${STARTERS.map(type=>`<option value="${type}" ${game.config.starterActivity===type?'selected':''}>${getCard(type).name}</option>`).join('')}</select></label><p>另发零散接单、听完整张专辑。起始牌仍需花行动安排。</p><div class="settings-grid">${Object.entries(fields).map(([key,name])=>`<label>${name}<input type="number" name="${key}" min="${key==='maxSanity'?1:0}" max="${key==='startSanity'?10:4294967295}" step="1" required value="${game.config[key]}"></label>`).join('')}</div><button class="primary-button" type="submit">开始新游戏</button></form>`;}
function summary(){return `${game.players.map(p=>`<section class="summary-player"><h3>${esc(p.name)} · ${p.escaped?'已逃离':game.phase==='ended'?'究极牛马':`副业 ${p.income}`}</h3><p>资金 ${p.money} · 理智 ${p.sanity}/10 · 技能 ${Object.entries(E.skillCounts(p)).map(([r,n])=>r+n).join(' ')}</p>${p.drafts.map(d=>`<p>「${esc(d.source)}」的候选 · 选择 1 张</p><div class="draft-options">${d.options.map(c=>`<article class="draft-card family-${familyOf(getCard(c))}">${face(getCard(c))}<button class="primary-button" data-action="draft" data-id="${p.id}" data-draft="${d.id}" data-uid="${c.uid}" ${p.bot?'disabled':''}>保留</button></article>`).join('')}</div>`).join('')}${game.phase==='escape'&&!Object.hasOwn(game.escapeDecisions,p.id)&&!p.bot?`<div class="split-buttons"><button class="primary-button" data-action="escape" data-id="${p.id}">逃离工位</button><button class="outline-button" data-action="stay" data-id="${p.id}">本周留下</button></div>`:''}${game.escapeDecisions[p.id]?'已选择逃离':''}</section>`).join('')}${game.phase==='escape'?`<button class="primary-button" data-action="next-week" ${game.players.some(p=>p.drafts.length||!Object.hasOwn(game.escapeDecisions,p.id))?'disabled':''}>${game.players.filter(p=>p.escaped||game.escapeDecisions[p.id]).length>=game.players.length-1?'结束本局':'进入下一周，公开新事件'}</button>`:'<p>逃离者获胜；没有额外终轮，也不以资金折算胜利。</p><button class="primary-button" data-action="settings">再玩一局</button>'}`;}
function modal(){let content,title;if(dialog==='detail'){const d=getCard(detail);title=d.name;content=`<div class="card-reference family-${familyOf(d)}">${face(d)}<p>${hours(d.size)}h · 购入 ${d.price.money} 资金 · ${d.progressTarget?`多周一次性 · 成功 ${d.progressTarget} 次完成`:d.once?'一次性':'每周重复'}${d.income?' · 副业收入':''}</p><p>${specialRules(d).join('；')}</p>${d.progressTarget?`<p>每次成功推进支付：${tokens(d.cost,'−')||'无'}。满 ${d.progressTarget} 格才结算完成效果；撤回与移动保留进度。</p>`:''}${d.stress?`<p>在日程中承担 ${d.stress} 压力，移出时解除；理智根据全部处境重算。门槛 ≥${d.minSanity||0} 在安排后及执行前检查。</p>`:''}</div>`;}else if(dialog==='rules'){title='玩家帮助 · v0.9';content=iconHelp()+rules();}else if(dialog==='settings'){title='开始新游戏';content=settings();}else if(dialog==='catalogue'){title='公开卡牌图鉴';content=`<p>只展示牌的定义，不展示暗牌顺序。所有高级牌都在 8h 堆。</p><div class="catalogue-v7">${[...CARDS,...ADVANCED].map(d=>`<button class="family-${familyOf(d)}" data-action="detail" data-type="${d.id}">${icon(d.icon,18)}<b>${d.name}</b><span>${hours(d.size)}h · ${d.price.money}元 ${d.requires||d.skill||''}</span></button>`).join('')}</div>`;}else{title=game.phase==='ended'?'工位之外 · 最终结果':`第 ${game.week} 周结算`;content=summary();}return `<div class="dialog-backdrop"><section class="dialog-panel ${dialog==='catalogue'?'catalogue-dialog':''}" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1"><button class="dialog-close icon-button" data-action="close" aria-label="关闭">${icon('x',20)}</button><h2 id="dialog-title">${title}</h2>${content}</section></div>`;}
function render(){const p=current(),scroll=document.querySelector('.calendar-scroll')?.scrollLeft||0;app.innerHTML=`<div class="app-shell"><header class="topbar"><a class="brand" href="/">${icon('exit',26)} 逃离工位 <small>v0.9</small></a><nav><button data-action="catalogue">${icon('layers',16)} 图鉴</button><button data-action="rules">玩家帮助</button><button data-action="export">导出</button><button data-action="settings">新游戏 / 数值</button></nav></header><div class="player-tabs">${game.players.map(q=>`<button data-action="player" data-id="${q.id}" class="player-tab ${q.id===playerId?'active':''}"><span class="avatar small" style="--avatar:${colors[q.id]}">${q.id+1}</span>${esc(q.name)} ${q.escaped?'已逃离':game.phase==='planning'&&E.activeBuyer(game)===q.id?'· 行动中':''}</button>`).join('')}</div><div class="quick-actions"><span>第 ${game.week} 周 · ${phaseNames[game.phase]} ${game.phase==='planning'?`/ ${DAYS[game.day]} · ${game.actionCount}/${game.players.length*7} 行动`:''}</span><div><button data-action="shelf" data-tab="hand">安排日程</button><button data-action="shelf" data-tab="market">购买 / 刷牌</button>${game.phase==='planning'?`<button data-action="pass" ${editable(p)?'':'disabled'}>整备 +${game.config.restMoney}元</button>`:game.phase==='resolving'?'<button class="primary-button" data-action="resolve">一键结算</button>':'<button data-action="summary">查看结算</button>'}</div></div>${selected?`<div class="selection-notice"><strong>${esc(getCard(E.cardAt(p,selected)).name)}</strong><span>点击绿色时段 · 安排或移动花 1 次行动</span><button data-action="cancel">取消选择</button></div>`:''}<div class="play-layout"><div class="main-column">${board(p)}<div class="tabletop-legend">${Object.entries(FAMILIES).filter(([k])=>k!=='time'&&k!=='work').map(([key,v])=>`<span class="family-key family-${key}">${icon(v.icon,14)}${v.name}</span>`).join('')}<span>− 消耗 / + 收益 / ≥ 理智门槛 / ↩ 可逆影响</span></div>${shelfPanel(p)}</div>${sidebar(p)}</div><footer class="page-footer">仅三个公共牌堆 · 每人每周七次行动 · 实体桌游测试版 · 旧 A4 图纸仍为 v0.6</footer></div>${dialog?modal():''}`;document.querySelector('.calendar-scroll').scrollLeft=scroll;if(dialog)document.querySelector('.dialog-close')?.focus({preventScroll:true});}
function act(fn){try{fn();selected=null;selectedSlot=null;if(game.phase==='planning'&&!game.players[E.activeBuyer(game)].bot)playerId=E.activeBuyer(game);if(['escape','ended'].includes(game.phase))dialog='summary';save();render();runBots();}catch(error){toast(error.message);}}
function runBots(){clearTimeout(botTimer);if(dialog==='settings')return;if(game.phase==='planning'&&game.players[E.activeBuyer(game)].bot)botTimer=setTimeout(()=>act(()=>E.botAct(game)),420);else if(game.phase==='escape'&&game.players.some(p=>p.bot&&(p.drafts.length||!Object.hasOwn(game.escapeDecisions,p.id))))botTimer=setTimeout(()=>act(()=>{for(const p of game.players.filter(p=>p.bot)){E.botDraft(game,p.id);if(!Object.hasOwn(game.escapeDecisions,p.id))E.chooseEscape(game,p.id);}}),250);}
function exportGame(){const url=URL.createObjectURL(new Blob([JSON.stringify({rulesVersion:'0.9',exportedAt:new Date().toISOString(),game},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`逃离工位-v09-第${game.week}周.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
app.addEventListener('click',event=>{const t=event.target.closest('[data-action]');if(!t||t.disabled)return;const a=t.dataset.action,p=current();
 if(['settings','rules','catalogue','summary'].includes(a)){dialog=a;if(a==='settings')clearTimeout(botTimer);render();return;}
 if(a==='close'){dialog=null;render();runBots();return;}if(a==='detail'){detail=t.dataset.type;dialog='detail';render();return;}if(a==='export'){exportGame();return;}
 if(a==='player'){playerId=Number(t.dataset.id);selected=null;selectedSlot=null;render();return;}
 if(a==='shelf'){shelf=t.dataset.tab;render();document.querySelector('#shelf').scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(a==='select'){selected=selected===t.dataset.uid?null:t.dataset.uid;selectedSlot=null;render();if(selected)document.querySelector('.calendar-panel').scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(a==='cancel'){selected=null;render();return;}
 if(a==='slot'){const s={day:Number(t.dataset.day),period:Number(t.dataset.period)};if(selected){const uid=selected;act(()=>E.place(game,p.id,uid,s));}else{selectedSlot=s;render();}return;}
 if(a==='buy'){act(()=>E.buy(game,p.id,t.dataset.uid));return;}if(a==='refresh'){act(()=>E.refresh(game,p.id,t.dataset.uid));return;}if(a==='pass'){act(()=>E.pass(game,p.id));return;}if(a==='unplace'){act(()=>E.unplace(game,p.id,t.dataset.uid));return;}
 if(a==='step'){act(()=>E.step(game));return;}if(a==='resolve'){act(()=>E.resolveAll(game));return;}if(a==='draft'){act(()=>E.chooseAdvanced(game,Number(t.dataset.id),t.dataset.draft,t.dataset.uid));return;}
 if(a==='escape'||a==='stay'){act(()=>E.chooseEscape(game,Number(t.dataset.id),a==='escape'));return;}if(a==='next-week'){act(()=>{E.closeWeek(game);dialog=game.phase==='ended'?'summary':null;});return;}
});
app.addEventListener('submit',event=>{if(event.target.id!=='settings-form')return;event.preventDefault();const data=Object.fromEntries(new FormData(event.target));for(const key of Object.keys(data))if(!['mode','starterActivity'].includes(key))data[key]=Number(data[key]);clearTimeout(botTimer);game=E.createGame(data);playerId=0;selected=null;selectedSlot=null;dialog=null;shelf='hand';save();render();runBots();});
app.addEventListener('input',event=>{if(event.target.id==='notes'){game.notes=event.target.value;save();}});
// Trap keyboard focus inside open dialogs; Escape resumes any paused bot turn.
app.addEventListener('keydown',event=>{if(event.key==='Tab'&&dialog){const items=[...document.querySelectorAll('.dialog-panel button:not(:disabled),.dialog-panel input,.dialog-panel select')];const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){dialog=null;selected=null;selectedSlot=null;render();runBots();}});
render();runBots();
