import {opportunityPanel} from './opportunity-ui.js';
import { DAYS, DEFAULTS, ROUTES, CARDS, ADVANCED, MARKET_LIMITS, getCard, slotKey, slotLabel } from './cards.js';
import * as E from './engine.js';
import { FAMILIES, familyOf, hours, specialRules } from './card-visuals.js';
import { icon } from './icons.js';
import { cardFace as face, iconHelp } from './card-face.js';
const STORAGE='escape-velocity-game-v20', app=document.querySelector('#app');
let investmentTarget=null;
function selectedInvestment(){const c=selected&&E.cardAt(current(),selected);return c?.lockedCapital;}
let game;try{const saved=JSON.parse(localStorage.getItem(STORAGE));if(saved?.version===20&&saved.sanityModel==='support-v1'&&saved.progressModel===1)game=saved;}catch{}
game ||= E.createGame();
// Fill new options when resuming an earlier v0.20 test save.
game.config={...DEFAULTS,...game.config};
// Recompute loaded bars too: completed skills no longer improve sanity.
for(const p of game.players) E.syncSanity(game,p);
let playerId=game.opportunity?.player??(game.phase==='planning'?E.activeBuyer(game):0), selected=null, selectedSlot=null, shelf=game.players[playerId].cards.length?'hand':'market', dialog=game.opportunity?'opportunity':null, detail=null, botTimer;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const resourceNames={money:'资金',sanity:'理智',inspiration:'灵感'};
const colors=['#42786b','#aa7650','#7766a0','#667f9b'];
const phaseNames={planning:'日程阶段',resolving:'结算阶段',escape:'周末复盘',ended:'终局'};
const current=()=>game.players[playerId];
const editable=p=>game.phase==='planning'&&E.activeBuyer(game)===p.id&&!p.bot;
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(game));}catch{}}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),3500);}
function tokens(values={},sign='+'){return Object.entries(values).filter(([,n])=>n).map(([key,n])=>`<span class="effect-token ${key}" title="${resourceNames[key]} ${sign}${n}">${icon(key,14)}<b>${sign}${n}</b></span>`).join('');}
function skillSymbols(pattern){return [...pattern].map(r=>`<span class="skill-symbol family-${ROUTES[r].family}" title="${ROUTES[r].name}">${icon(ROUTES[r].icon,12)}${r}</span>`).join('');}
function cardTile(c,context,p){const d=getCard(c),where=context==='hand'?E.findPlacement(p,c.uid):null,can=editable(p),available=context==='market'?can&&E.canPay(p,d.price):can&&E.qualified(p,d)&&(!where||where.day>=game.day);
 return `<article class="game-card family-${familyOf(d)} ${selected===c.uid?'card-selected':''}" data-hours="${hours(d.size)}" style="--card-hours:${hours(d.size)}"><div class="card-paper">${face(d,false,c)}</div><div class="card-bottom"><button class="detail-button" data-action="detail" data-type="${d.id}" aria-label="${esc(d.name)}详情">${icon('info',15)}</button>${context==='market'?`<button data-action="buy" data-uid="${c.uid}" ${available?'':'disabled'}>购买</button>`:`<button data-action="select" data-uid="${c.uid}" ${available?'':'disabled'}>${selected===c.uid?'已选':where?'移动':E.qualified(p,d)?'安排':'缺技能'}</button>${where?`<button data-action="unplace" data-uid="${c.uid}" ${can&&where.day>=game.day?'':'disabled'} title="用一次行动撤回">${icon('undo',14)}</button>`:''}`}</div>${where?`<small class="card-location">${slotLabel(where)}</small>`:''}</article>`;
}
function slotTile(p,s){const initial=E.cardsInSlot(p,s),merged=s.period===0&&initial.some(c=>getCard(c).hours===8),list=merged?[...new Map([...initial,...E.cardsInSlot(p,{day:s.day,period:1})].map(c=>[c.uid,c])).values()]:initial,full=list.some(c=>hours(getCard(c).size)===8),h=full?8:E.slotHours(p,s),work=E.workType(p,s),past=game.phase==='planning'&&s.day<game.day,blocked=(full?E.coveredSlots(getCard(list.find(c=>getCard(c).hours===8)),s):[s]).some(t=>E.eventBlocksSlot(game,p,t)),caught=list.some(c=>!getCard(c).professional&&E.coveredSlots(getCard(c),s).some(t=>E.inspected(game,p,t)&&!E.protectedActivity(p,c,t))),allowed=selected&&editable(p)&&!E.canPlace(game,p,selected,s,selectedInvestment()),chosen=selectedSlot&&slotKey(selectedSlot)===slotKey(s),isNight=s.period===2;
 return `<div class="slot-track ${isNight?'night-track':''} ${full?'full-day-track':''}" style="--slot-hours:${full?8:4}"><span class="slot-caption">${icon(isNight?'moon':'sun',12)} ${full?'上午—下午':['上午','下午','夜晚'][s.period]}<b>${h||0}/${full?8:4}h</b></span><div class="physical-well ${caught?'inspected':''} ${allowed?'placeable':''} ${chosen?'selected-slot':''} ${past?'past-slot':''} ${blocked?'blocked-slot':''}"><button class="slot v7-slot ${isNight?'night-slot':''}" data-action="slot" data-day="${s.day}" data-period="${s.period}" aria-label="${full?DAYS[s.day]+'全天':slotLabel(s)}${caught?'，查岗命中':''}${blocked?'，团建占用':''}" ${past?'disabled':''}>${list.length?'<div class="'+(full&&list.length===2?'full-parallel-stack':list.length===2&&list.some(c=>getCard(c).parallel)?'parallel-stack':'activity-stack')+'">'+[...list].sort((a,b)=>full?getCard(b).hours-getCard(a).hours:0).map(c=>face(getCard(c),true,c)).join('')+'</div>':`<div class="${isNight?'night-rest-content':work?'work-content':'free-content'}">${isNight&&p.inspirationSlots.includes(slotKey(s))?'<span class="board-inspiration" title="版图灵感，不消耗">'+icon('inspiration',28)+'</span>':icon(isNight?'moon':work||'leaf',28)}<strong>${isNight?(p.inspirationSlots.includes(slotKey(s))?'留白 · 灵感':'休息'):work==='meeting'?'开会':work?'坐班':'自由时光'}</strong><small>${isNight?'≤2h 不扣理智':work?'可直接安排摸鱼':'可安排一张活动'}</small></div>`}</button>${full?`<div class="parallel-targets"><button data-action="slot" data-day="${s.day}" data-period="0" ${past?'disabled':''}>上午 ∥</button><button data-action="slot" data-day="${s.day}" data-period="1" ${past?'disabled':''}>下午 ∥</button></div>`:''}${caught?`<span class="slot-badge danger">${icon('eye',12)} 查岗 · 每张 −${game.config.inspectionFine}元</span>`:blocked?'<span class="slot-badge danger">团建 · 本周暂停</span>':isNight&&h>2?`<span class="slot-badge danger">熬夜压力 ${E.nightStress(game,h)}</span>`:h&&work?`<span class="slot-badge">${list.every(c=>getCard(c).professional)?'履职 · 免查岗':'摸鱼 '+h+'h · '+(game.inspectionResolved?'未命中':'日期未知')}</span>`:''}</div></div>`;
}
function resources(p){return `<div class="resources">${[['money',p.money,'资金'],['sanity',p.sanity,'理智'],['inspiration',E.inspirationCount(p),'版图灵感']].map(([k,n,label])=>`<div class="resource"><span class="resource-icon ${k}">${icon(k,22)}</span><div><span>${label}</span><strong>${n}</strong></div></div>`).join('')}</div><div class="sanity-track" aria-label="理智指标 ${p.sanity}，范围 0 到 10"><span>${icon('sanity',16)} 理智</span><div class="sanity-scale" style="--sanity-fill:${p.sanity*10}%">${Array.from({length:11},(_,n)=>`<span class="sanity-tick ${n===p.sanity?'current':''}" ${n===p.sanity?'aria-current="true"':''}>${n}</span>`).join('')}</div><small>≥ 门槛 · 处境决定状态</small></div><p class="sanity-explanation">起点 ${game.config.startSanity} · 自主 ${E.sanityState(game,p).freedom} · 支持 +${E.sanityState(game,p).support} · 日程压力 ${E.sanityState(game,p).pressure} · 支持费 ${E.sanityState(game,p).upkeep}/周${game.phase==='planning'?'（按当前资金试算，查岗后确认）':''}</p>`;}
function board(p){const counts=E.skillCounts(p);return `<section class="calendar-panel"><div class="panel-heading"><div><span class="section-kicker">PERSONAL PLAYER BOARD</span><h2>${esc(p.name)}的工位之外</h2></div><span class="subtle">${p.escaped?'已逃离':p.weekend?'永久双休':p.tempWeekend?'本周双休':'周一至周六工作'}</span></div>${resources(p)}<div class="calendar-scroll"><div class="calendar-grid">${DAYS.map((day,i)=>`<div class="day-lane ${!E.workType(p,{day:i,period:0})?'free-day':''} ${game.phase==='planning'&&i===game.day?'current-day':''}"><div class="day-heading"><span class="day-number">${i+1}</span><strong>${day}</strong>${game.phase==='planning'&&i<game.day?icon('lock',12):''}</div>${[0,1,2].map(period=>period===1&&E.cardsInSlot(p,{day:i,period:0}).some(c=>hours(getCard(c).size)===8)?'':slotTile(p,{day:i,period})).join('')}</div>`).join('')}</div></div><div class="calendar-footer">∥ 可与一张牌并行，时间取较长者 · 灵感放在空夜，放牌清除 · 8h 占全天</div><section class="skill-tray">${Object.entries(ROUTES).map(([r,info])=>`<details class="skill-stack family-${info.family}"><summary>${icon(info.icon,20)} ${info.name} <b>${counts[r]}</b></summary>${p.skills.filter(c=>getCard(c).skill===r).map(c=>`<span class="skill-slip">${getCard(c).name}</span>`).join('')||'<small>完成一次性活动留下经历</small>'}</details>`).join('')}</section>${p.upgrades.length?`<div class="upgrades-tray">${p.upgrades.map(c=>`<button class="upgrade-plaque family-${familyOf(getCard(c))}" data-action="detail" data-type="${c.type}">${icon('achievement',20)}${getCard(c).name} · ${c.activeFrom>game.week?'下周生效':'已生效'}</button>`).join('')}</div>`:''}</section>`;}
function editor(p){if(!selectedSlot)return '';const s=selectedSlot,cards=E.cardsInSlot(p,s);return `<section class="slot-editor"><h3>${slotLabel(s)}</h3>${cards.map(c=>`<div class="edit-row"><button data-action="detail" data-type="${c.type}">${esc(getCard(c).name)}</button><button data-action="select" data-uid="${c.uid}" ${editable(p)&&s.day>=game.day?'':'disabled'}>${getCard(c).capitalRatio?'移动 / 调本金':'移动'}</button><button data-action="unplace" data-uid="${c.uid}" ${editable(p)&&s.day>=game.day?'':'disabled'}>撤回</button></div>`).join('')||'<p>从手牌选一张，再点此时段安排。</p>'}<small>移动、撤回各花一次行动。替换需要先撤回，再安排。</small></section>`;}
function marketRefreshNotice(){return game.phase==='planning'&&game.day===0?(game.mondayMarketBought?'周一已有在职玩家购牌：本周不整批刷新。':'周一尚无在职玩家购牌：若本日结束仍无人购买，将刷新全部市场。安排、移动、撤回和躺平不阻止刷新。'):game.mondayMarketRefreshed?'本周已触发周一市场刷新，下次检查在下周一。':'本周周一已有在职玩家购牌，市场保留。';}
function sidebar(p){
 const prediction=game.phase==='planning'?E.preview(game,p.id):null;
 const diceLogs=game.logs.filter(l=>l.week===game.week&&l.tone==='dice').slice(-5);
 return `<aside class="sidebar"><section class="phase-card"><span class="section-kicker">WEEK ${game.week}</span><h3>${phaseNames[game.phase]}</h3>${game.phase==='planning'?`<p><b>${DAYS[game.day]} · ${esc(game.players[E.activeBuyer(game)].name)}</b>行动</p><p>① 买一张牌<br>② 安排 / 移动 / 撤回一张<br>③ 躺平：跳过行动</p><p>今日躺平 ${game.dayPasses||0}/${game.players.length} 人；全员躺平立即结算本周。</p><button class="primary-button" data-action="pass" ${editable(p)?'':'disabled'}>躺平 · 跳过行动</button>`:game.phase==='resolving'?`<p>日程已锁定 · 已结算 ${game.cursor}/${game.timeline.length} 时段</p>${game.opportunity?'<button class="primary-button" data-action="opportunity">处理寻找机会</button>':''}<button class="primary-button" data-action="step" ${game.opportunity?'disabled':''}>${game.inspectionResolved?'下一时段':'掷公共查岗骰'}</button><button class="outline-button" data-action="resolve" ${game.opportunity?'disabled':''}>结算至下一次选择</button>`:`<button class="primary-button" data-action="summary">查看结算</button>`}</section>
 <section class="phase-card"><h3>市场流动</h3><p>${marketRefreshNotice()}</p></section>
 <section class="inspection-card"><span class="section-kicker">公共事件 · ${game.inspectionResolved?'已揭晓':'日期隐藏'}</span><h3>${esc(game.inspection.name)}</h3><p>${esc(game.inspection.text)}</p>${game.inspectionResolved?`<div class="inspection-dice">${game.inspection.rolls.map(n=>`<span title="${DAYS[n-1]}">${'⚀⚁⚂⚃⚄⚅'[n-1]}<small>${DAYS[n-1]}</small></span>`).join('')||'本周无查岗'}</div>`:`<p class="dice-hidden">${'□ '.repeat(game.inspection.inspectionCount||0)}${game.inspection.inspectionCount?'排完后掷骰，全体共用':'本周无查岗'}</p>`}<small>抓包：每张 −${game.config.inspectionFine} 钱；整项暂停；无额外理智惩罚；支持牌被查停则失去支持。</small></section>
 <section class="escape-card"><h3>逃离：副业 ≥${game.config.escapeIncome} · 理智 ≥${game.config.escapeSanity}</h3><p>当前理智 ${E.sanityState(game,p).value}/10${E.sanityState(game,p).value<game.config.escapeSanity?' · 尚未达标':' · 已达标'}</p><p>周末汇总成功副业，再检查逃离条件。</p>${prediction?`<details><summary>查看副业试算</summary><strong class="projected-income">${prediction.incomeLow===prediction.incomeHigh?prediction.incomeHigh:prediction.incomeLow+'–'+prediction.incomeHigh}</strong><p>未被查停时，活动骰最低 / 最高点数的试算；并非保证收益。</p></details>`:p.settlement?`<p>本周副业合计：${p.income}</p>`:''}${prediction?.warnings.length?`<details><summary>${prediction.warnings.length} 项执行限制</summary>${prediction.warnings.map(l=>`<p>${esc(l.text)}</p>`).join('')}</details>`:''}<small>副业收入不封顶。工资、奖金和返还本金不计门槛。</small></section>
 ${p.protectionFrom<=game.week&&!p.escaped?`<section class="phase-card"><h3>弹性保护</h3>${p.protectionChosen?`本周保护：${slotLabel({day:Number(p.protectedSlot[0]),period:Number(p.protectedSlot[2])})}`:!p.actedThisWeek?`<select id="protection-slot" aria-label="保护时段">${DAYS.slice(0,6).flatMap((_,day)=>[0,1].filter(period=>E.workType(p,{day,period})).map(period=>`<option value="${day}-${period}">${slotLabel({day,period})}</option>`)).join('')}</select><button data-action="protect" ${editable(p)?'':'disabled'}>锁定保护（不耗行动）</button>`:'本周未指定保护'}<p>保护该格最先安排的一张 2h / 4h 活动；首次行动前选定。</p></section>`:''}
 ${diceLogs.length?`<section class="phase-card"><h3>最近骰子记录</h3>${diceLogs.map(l=>`<p>${esc(l.text)}</p>`).join('')}</section>`:''}${editor(p)}</aside>`;
}
function shelfPanel(p){return `<section class="shelf-panel" id="shelf"><div class="shelf-header"><div class="shelf-tabs">${[['hand','我的卡牌'],['market','公共市场'],['log','本周记录']].map(([id,name])=>`<button data-action="shelf" data-tab="${id}" class="${shelf===id?'active':''}">${name}</button>`).join('')}</div><span class="shelf-hint">${shelf==='market'?'2h ×5 · 4h ×4 · 8h ×3 · 买后立即补位':'图标说明见玩家帮助 · 悬停可查看含义'}</span></div>${shelf==='hand'?`<p class="hand-hint">选择卡牌，再点击绿色时段。手牌 ${E.unplacedCards(p).length} 张；已安排牌也显示在这里，便于移动。</p><div class="hand-grid">${p.cards.map(c=>cardTile(c,'hand',p)).join('')}</div>${p.completedActivities.length?`<section class="permanent-effects"><h3>永久效果</h3>${p.completedActivities.map(c=>`<button data-action="detail" data-type="${c.type}">${icon(getCard(c).icon,18)} ${getCard(c).name} · 已完成</button>`).join('')}</section>`:''}`:shelf==='market'?`<p class="hand-hint">${marketRefreshNotice()}</p><div class="market-groups">${Object.entries(MARKET_LIMITS).map(([h,n])=>`<section class="duration-market"><div class="market-label"><span>${h}h 活动</span><small>${n} 展示位 · 牌堆 ${game.decks[h].length} · 弃牌 ${game.discard[h].length}</small></div><div class="market-grid">${game.market[h].map(c=>cardTile(c,'market',p)).join('')}</div></section>`).join('')}</div>`:`<div class="log-panel"><div class="log-list">${game.logs.filter(l=>l.week===game.week).slice().reverse().map(l=>`<div class="log-row"><span class="log-dot ${l.tone}"></span><strong>${l.player===null?'全体':esc(game.players[l.player].name)}</strong><p>${esc(l.text)}</p></div>`).join('')}</div><div class="notes-panel"><h3>测试笔记</h3><textarea id="notes" placeholder="记录卡手、策略与节奏…">${esc(game.notes||'')}</textarea><button data-action="export">导出整局记录</button></div></div>`}</section>`;}
function rules(){return '<div class="rules-grid">'+[
 ['一天一次行动','从周一到周日，玩家交替行动：买牌、安排/移动/撤回、躺平三选一。只能修改当日及以后的日程；买牌不自动安排。同一天全体玩家均躺平，立即结束安排，完整结算本周已有日程。单独躺平不放弃后续日期的行动。'],
 ['隐藏查岗','周初仅预告掷骰次数。全员日程锁定后，D6 的 1–6 对应周一至周六，查当天上午与下午。全体共用结果，重复不重掷。被查活动暂停且不付执行消耗；每张固定罚 '+game.config.inspectionFine+' 钱，8h 不重复处罚。履职、已放假的日期和夜晚不受查岗。'],
 ['活动骰','仅一次性职场活动「向上管理」在执行时掷一次，先付消耗再掷骰，零收益不退投入；同名牌各掷各的。常驻创作与商业牌使用固定收益，再算条件及增强；单项与每周副业收入均不封顶。绿色中高级牌以并行释放时间，不再翻倍收入。'],
 ['日程与理智','2h/4h 占一个白天槽，8h 占两个半天且下午结算一次。晚间最多 4h；2h 没有夜间压力，4h 夜间压力 '+game.config.nightStress4+'。理智是 0–10 的状态：起点＋自主＋有效支持－日程压力。支持不累加；揭晓查岗后、活动前，按日程顺序付每周维持费。付不起维持费则撤回手牌；查停、团建或同晚超过2h则支持失效；当周工资与活动收入不能补缴。重复活动付不起执行消耗时撤回手牌，解除支持与压力并返还本金。安排后和执行前都检查上下限。'],
 ['四色卡池','灰色履职积累工资与信用，红色保留版图灵感，绿色并行，黄色投入本金和招募。市场 58 种（含4种付费生活牌、多种混合支持牌、5种重复找牌活动）；2h/4h/8h 亮 5/4/3 张，购买后刷新。每种高级 1 张，普通每种每人 1 张；开局没有活动手牌，须从公共市场购买。'],
 ['成长与永久效果','归档不消耗，同名只算一次，W 不能替代 ABC。技能只限制安排。双休需要 WW 信用，从 8h 公共牌堆购入，再另行安排；此前完成副业，每次花 1，三周完成。弹性授权来自 4h 公共牌堆，需 WW，完成后下周起在首次行动前保护一个时段中的 2h / 4h 活动。'],
 ['留白、并行与本金','周初每个空置夜晚放1枚灵感，每格最多1枚；放牌清除，撤回不立即补回。灵感不花费。∥牌可与一张活动共用时段，时间取较长者，各自承担费用和压力。稳定供货每4本金产生1收入，自有品牌每3本金产生1收入；安排时选定，调整花一次行动，撤回返还。无收入上限。'],
 ['寻找与招募','找牌活动每周执行：任选一个时长牌堆，看N张，原价买至多1张，余牌放堆底；新牌下周再安排。招募伙伴：额外支付2钱，原价购买市场中一张2h一次性牌直接归档，不执行原效果；可放弃，放弃不收费。研讨会仍在周末免费取得同色高级牌。'],
 ['周一市场刷新','周一所有玩家行动结束时，若尚未逃离的玩家均未购买公共市场牌，立即刷新全部市场；若当天全员躺平则直接结算，新市场留到下周，否则继续周二。安排、移动、撤回、躺平都不阻止刷新。旧明牌先放一旁，补新牌后放回对应牌堆底；牌源不足时旧牌可补回空位。每周只检查一次，已逃离者购牌不影响判定。'],
 ['周结与胜负','固定工资 '+game.config.salary+'，无生活费。躺平不获得资源；同日全员躺平提前结束安排，已安排活动照常执行。当周副业达到 '+game.config.escapeIncome+' 且理智至少 '+game.config.escapeSanity+' 可逃离。没有副业轨道，总额不封顶。活动资金收益先记账，全部日程结束后与工资、事件收入一起领取；不能用于本周后续活动。灵感是版图状态，执行只检查不扣除。N−1 人逃离当周结束，未逃离为究极牛马。工资、奖金不计逃离。']
 ].map(([title,text])=>'<article><h3>'+title+'</h3><p>'+text+'</p></article>').join('')+'</div>';}
function settings(){const fields={startMoney:'起始资金',startSanity:'起始理智',salary:'每周工资',nightStress4:'4h 熬夜压力',escapeIncome:'逃离收入门槛',escapeSanity:'逃离理智门槛',inspectionFine:'每张抓包罚款',seed:'随机种子'};return `<p>v0.20：双休与弹性授权并入公共牌堆，完成后留下永久效果牌。取消开局赠牌，所有玩家空手开始。躺平仅跳过行动，每周固定工资默认 3 钱；活动资金在周末统一领取，付不起执行消耗的重复活动撤回手牌，解除支持与压力并返还本金。无副业轨道。旧存档单独保留。默认抓包每张罚 1 钱，与活动时长无关。</p><form id="settings-form"><div class="setup-row"><label>人数<select name="playerCount">${[2,3,4].map(n=>`<option ${n===game.config.playerCount?'selected':''}>${n}</option>`).join('')}</select></label><label>方式<select name="mode"><option value="bots" ${game.config.mode==='bots'?'selected':''}>你 + 自动玩家</option><option value="hotseat" ${game.config.mode==='hotseat'?'selected':''}>同机轮流</option></select></label></div><p>开局无活动手牌；从公共市场购买，再花行动安排。</p><div class="settings-grid">${Object.entries(fields).map(([key,name])=>`<label>${name}<input type="number" name="${key}" min="${key==='escapeIncome'?1:0}" max="${['startSanity','escapeIncome','escapeSanity'].includes(key)?10:4294967295}" step="1" required value="${game.config[key]}"></label>`).join('')}</div><button class="primary-button" type="submit">开始新游戏</button></form>`;}
function weeklyBill(p){const b=p.settlement;if(!b)return '';return `<div class="weekly-bill"><p>副业 <b>${b.sideIncome}</b> ＋ 工资 ${b.salary} ＋ 其他活动 ${b.otherIncome} ＋ 事件 ${b.eventMoney}</p><strong>本周统一领取 ${b.total} 资金</strong><small>已付费用不重复扣除；只有副业合计用于逃离门槛。</small><details><summary>活动收入明细</summary>${p.weeklyEarnings.filter(x=>x.money||x.profit).map(x=>`<p>${esc(getCard(x.type).name)}：${x.money} 资金${x.profit?`（副业 ${x.profit}）`:''}</p>`).join('')||'<p>本周无活动资金收入。</p>'}</details></div>`;}
function summary(){return `<div class="summary-dice"><strong>本周查岗骰：</strong>${game.inspection.rolls.map(n=>'⚀⚁⚂⚃⚄⚅'[n-1]+' '+DAYS[n-1]).join(' / ')||'无查岗'}<p>活动骰结果见本周记录；同一结果在刷新页面后保持。</p></div>${game.players.map(p=>`<section class="summary-player"><h3>${esc(p.name)} · ${p.escaped?'已逃离':game.phase==='ended'?'究极牛马':`副业 ${p.income}`}</h3>${weeklyBill(p)}<p>资金 ${p.money} · 理智 ${p.sanity}/10（逃离 ≥${game.config.escapeSanity}） · 技能 ${Object.entries(E.skillCounts(p)).map(([r,n])=>r+n).join(' ')}</p>${p.drafts.map(d=>`<p>「${esc(d.source)}」的候选 · 选择 1 张</p><div class="draft-options">${d.options.map(c=>`<article class="draft-card family-${familyOf(getCard(c))}">${face(getCard(c))}<button class="primary-button" data-action="draft" data-id="${p.id}" data-draft="${d.id}" data-uid="${c.uid}" ${p.bot?'disabled':''}>保留</button></article>`).join('')}</div>`).join('')}${game.phase==='escape'&&!Object.hasOwn(game.escapeDecisions,p.id)&&!p.bot?`<div class="split-buttons"><button class="primary-button" data-action="escape" data-id="${p.id}">逃离工位</button><button class="outline-button" data-action="stay" data-id="${p.id}">本周留下</button></div>`:''}${game.escapeDecisions[p.id]?'已选择逃离':''}</section>`).join('')}${game.phase==='escape'?`<button class="primary-button" data-action="next-week" ${game.players.some(p=>p.drafts.length||!Object.hasOwn(game.escapeDecisions,p.id))?'disabled':''}>${game.players.filter(p=>p.escaped||game.escapeDecisions[p.id]).length>=game.players.length-1?'结束本局':'进入下一周，公开新事件'}</button>`:'<p>逃离者获胜；没有额外终轮，也不以资金折算胜利。</p><button class="primary-button" data-action="settings">再玩一局</button>'}`;}
function modal(){let content,title;if(dialog==='invest'){title='安排经营';const c=E.cardAt(current(),investmentTarget.uid),d=getCard(c);content='<p>每 '+d.capitalRatio+' 本金 → 1 收入。调整占用一次安排行动，撤回返还。</p><label>投入本金<input id="investment-value" type="number" step="'+d.capitalRatio+'" min="'+d.capitalRatio+'" max="'+(current().money+(c.lockedCapital||0))+'" value="'+(c.lockedCapital||d.capitalRatio)+'"></label><button class="primary-button" data-action="invest-confirm">确认安排</button>';}else if(dialog==='opportunity'){title='寻找机会';content=opportunityPanel(game);}else if(dialog==='detail'){const d=getCard(detail);title=d.name;content=`<div class="card-reference family-${familyOf(d)}">${face(d)}<p>${hours(d.size)}h · 购入 ${d.price.money} 资金 · ${d.progressTarget?`多周一次性 · 成功 ${d.progressTarget} 次完成`:d.once?'一次性':'每周重复'}${d.income?' · 副业收入':''}</p><p>${specialRules(d).join('；')}</p>${d.progressTarget?`<p>每次成功推进支付：${tokens(d.cost,'−')||'无'}。满 ${d.progressTarget} 格才结算完成效果；撤回与移动保留进度。</p>`:''}${d.stress?`<p>在日程中承担 ${d.stress} 压力，移出时解除；理智根据全部处境重算。门槛 ${d.maxSanity<10?'≤'+d.maxSanity:'≥'+d.minSanity} 在安排后及执行前检查。</p>`:''}</div>`;}else if(dialog==='rules'){title='玩家帮助 · v0.20';content=iconHelp()+rules();}else if(dialog==='settings'){title='开始新游戏';content=settings();}else if(dialog==='catalogue'){title='公开卡牌图鉴';content=`<p>只展示牌的定义，不展示暗牌顺序。高级牌按实际时长分布在三个牌堆。</p><div class="catalogue-v7">${[...CARDS,...ADVANCED].map(d=>`<button class="family-${familyOf(d)}" data-action="detail" data-type="${d.id}">${icon(d.icon,18)}<b>${d.name}</b><span>${hours(d.size)}h · ${d.price.money}元 ${d.requires||d.skill||''}</span></button>`).join('')}</div>`;}else{title=game.phase==='ended'?'工位之外 · 最终结果':`第 ${game.week} 周结算`;content=summary();}return `<div class="dialog-backdrop"><section class="dialog-panel ${dialog==='catalogue'?'catalogue-dialog':''}" role="dialog" aria-modal="true" aria-labelledby="dialog-title" tabindex="-1"><button class="dialog-close icon-button" data-action="close" aria-label="关闭">${icon('x',20)}</button><h2 id="dialog-title">${title}</h2>${game.opportunity&&dialog!=='opportunity'?'<button class="outline-button" data-action="opportunity">返回寻找机会</button>':''}${content}</section></div>`;}
function render(){const p=current(),scroll=document.querySelector('.calendar-scroll')?.scrollLeft||0;app.innerHTML=`<div class="app-shell"><header class="topbar"><a class="brand" href="/">${icon('exit',26)} 逃离工位 <small>v0.20</small></a><nav><button data-action="catalogue">${icon('layers',16)} 图鉴</button><button data-action="rules">玩家帮助</button><button data-action="export">导出</button><button data-action="settings">新游戏 / 数值</button></nav></header><div class="player-tabs">${game.players.map(q=>`<button data-action="player" data-id="${q.id}" class="player-tab ${q.id===playerId?'active':''}"><span class="avatar small" style="--avatar:${colors[q.id]}">${q.id+1}</span>${esc(q.name)} ${q.escaped?'已逃离':game.phase==='planning'&&E.activeBuyer(game)===q.id?'· 行动中':''}</button>`).join('')}</div><div class="quick-actions"><span>第 ${game.week} 周 · ${phaseNames[game.phase]} ${game.phase==='planning'?`/ ${DAYS[game.day]} · ${game.actionCount}/${game.players.length*7} 行动`:''}</span><div><button data-action="shelf" data-tab="hand">安排日程</button><button data-action="shelf" data-tab="market">公共市场</button>${game.phase==='planning'?`<button data-action="pass" ${editable(p)?'':'disabled'}>躺平</button>`:game.phase==='resolving'?game.opportunity?'<button class="primary-button" data-action="opportunity">处理寻找机会</button>':'<button class="primary-button" data-action="resolve">继续结算</button>':'<button data-action="summary">查看结算</button>'}</div></div>${selected?`<div class="selection-notice"><strong>${esc(getCard(E.cardAt(p,selected)).name)}</strong><span>点击绿色时段 · 安排或移动花 1 次行动</span><button data-action="cancel">取消选择</button></div>`:''}<div class="play-layout"><div class="main-column">${board(p)}<div class="tabletop-legend">${Object.entries(FAMILIES).filter(([k])=>['career','creative','technical','business'].includes(k)).map(([key,v])=>`<span class="family-key family-${key}">${icon(v.icon,14)}${v.name}</span>`).join('')}<span>− 消耗 / + 收益 / ≥ 理智门槛 / ↩ 可逆影响</span></div>${shelfPanel(p)}</div>${sidebar(p)}</div><footer class="page-footer">仅三个公共牌堆 · 每人每周最多七次行动 · 同日全员躺平提前结算 · 实体桌游测试版 · 旧 A4 图纸仍为 v0.6</footer></div>${dialog?modal():''}`;document.querySelector('.calendar-scroll').scrollLeft=scroll;if(dialog)document.querySelector('.dialog-close')?.focus({preventScroll:true});}
function act(fn){try{fn();selected=null;selectedSlot=null;if(game.phase==='planning'&&!game.players[E.activeBuyer(game)].bot)playerId=E.activeBuyer(game);if(['escape','ended'].includes(game.phase))dialog='summary';if(game.opportunity){dialog='opportunity';playerId=game.opportunity.player;}else if(dialog==='opportunity')dialog=null;save();render();runBots();}catch(error){toast(error.message);}}
function runBots(){clearTimeout(botTimer);if(dialog==='settings')return;if(game.opportunity&&game.players[game.opportunity.player].bot)botTimer=setTimeout(()=>act(()=>E.botOpportunity(game)),420);else if(game.phase==='planning'&&game.players[E.activeBuyer(game)].bot)botTimer=setTimeout(()=>act(()=>E.botAct(game)),420);else if(game.phase==='escape'&&game.players.some(p=>p.bot&&(p.drafts.length||!Object.hasOwn(game.escapeDecisions,p.id))))botTimer=setTimeout(()=>act(()=>{for(const p of game.players.filter(p=>p.bot)){E.botDraft(game,p.id);if(!Object.hasOwn(game.escapeDecisions,p.id))E.chooseEscape(game,p.id);}}),250);}
function exportGame(){const url=URL.createObjectURL(new Blob([JSON.stringify({rulesVersion:'0.20',exportedAt:new Date().toISOString(),game},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`逃离工位-v20-第${game.week}周.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
app.addEventListener('click',event=>{const t=event.target.closest('[data-action]');if(!t||t.disabled)return;const a=t.dataset.action,p=current();
 if(['settings','rules','catalogue','summary','opportunity'].includes(a)){dialog=a;if(a==='settings')clearTimeout(botTimer);render();return;}
 if(a==='close'){dialog=null;render();runBots();return;}if(a==='detail'){detail=t.dataset.type;dialog='detail';render();return;}if(a==='export'){exportGame();return;}
 if(a==='player'){playerId=Number(t.dataset.id);selected=null;selectedSlot=null;render();return;}
 if(a==='shelf'){shelf=t.dataset.tab;render();document.querySelector('#shelf').scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(a==='select'){selected=selected===t.dataset.uid?null:t.dataset.uid;selectedSlot=null;render();if(selected)document.querySelector('.calendar-panel').scrollIntoView({behavior:'smooth',block:'start'});return;}
 if(a==='cancel'){selected=null;render();return;}
 if(a==='slot'){const s={day:Number(t.dataset.day),period:Number(t.dataset.period)};if(selected){const uid=selected;if(getCard(E.cardAt(p,uid)).capitalRatio){investmentTarget={uid,s};dialog='invest';render();}else act(()=>E.place(game,p.id,uid,s));}else{selectedSlot=s;render();}return;}
 if(a==='invest-confirm'){const amount=Number(document.querySelector('#investment-value').value);act(()=>{E.place(game,p.id,investmentTarget.uid,investmentTarget.s,amount);dialog=null;investmentTarget=null;});return;}
 if(a==='protect'){const [day,period]=document.querySelector('#protection-slot').value.split('-').map(Number);act(()=>E.setProtection(game,p.id,{day,period}));return;}if(a==='buy'){act(()=>E.buy(game,p.id,t.dataset.uid));return;}if(a==='pass'){act(()=>E.pass(game,p.id));return;}if(a==='unplace'){act(()=>E.unplace(game,p.id,t.dataset.uid));return;}
 if(a.startsWith('opp-')){act(()=>{
  const id=game.opportunity?.player;if(id===undefined||game.players[id].bot)throw Error('请等待自己的找牌选择。');
  if(a==='opp-hire')E.chooseHire(game,id,t.dataset.uid);
  else if(a==='opp-hire-skip')E.chooseHire(game,id);
  else if(a==='opp-lane')E.chooseOpportunityLane(game,id,Number(t.dataset.lane));
  else if(a==='opp-buy')E.chooseOpportunity(game,id,t.dataset.uid);
  else if(a==='opp-skip')E.chooseOpportunity(game,id);
 });return;}
 if(a==='step'){act(()=>E.step(game));return;}if(a==='resolve'){act(()=>E.resolveAll(game));return;}if(a==='draft'){act(()=>E.chooseAdvanced(game,Number(t.dataset.id),t.dataset.draft,t.dataset.uid));return;}
 if(a==='escape'||a==='stay'){act(()=>E.chooseEscape(game,Number(t.dataset.id),a==='escape'));return;}if(a==='next-week'){act(()=>{E.closeWeek(game);dialog=game.phase==='ended'?'summary':null;});return;}
});
app.addEventListener('submit',event=>{if(event.target.id!=='settings-form')return;event.preventDefault();const data=Object.fromEntries(new FormData(event.target));for(const key of Object.keys(data))if(key!=='mode')data[key]=Number(data[key]);clearTimeout(botTimer);game=E.createGame(data);playerId=0;selected=null;selectedSlot=null;dialog=null;shelf='market';save();render();runBots();});
app.addEventListener('input',event=>{if(event.target.id==='notes'){game.notes=event.target.value;save();}});
// Trap keyboard focus inside open dialogs; Escape resumes any paused bot turn.
app.addEventListener('keydown',event=>{if(event.key==='Tab'&&dialog){const items=[...document.querySelectorAll('.dialog-panel button:not(:disabled),.dialog-panel input,.dialog-panel select')];const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){dialog=null;selected=null;selectedSlot=null;render();runBots();}});
render();runBots();
