import {getCard} from './cards.js';
import {canPay} from './engine.js';
import {familyOf} from './card-visuals.js';
import {cardFace} from './card-face.js';

export function opportunityPanel(g){
 const q=g.opportunity;
 if(!q)return '<p>本次寻找已完成，可以继续结算。</p>';
 const p=g.players[q.player],disabled=p.bot?'disabled':'';
 const header=`<p class="opportunity-owner">玩家 ${p.id+1} · ${q.source} <span>资金 ${p.money} · 灵感 ${p.inspiration}</span></p><p>执行消耗已支付，活动已归档。可原价买至多一张，不另花行动，下周才能安排。技能门槛在安排时检查。</p>`;
 if(q.stage==='lane')return header+`<div class="opportunity-lanes">${[2,4,8].map(h=>`<button data-action="opp-lane" data-lane="${h}" ${disabled}><b>${h}h 牌堆</b><span>翻 ${q.count} 张</span><small>暗牌 ${g.decks[h].length} · 弃牌 ${g.discard[h].length}</small></button>`).join('')}</div><p>三堆任选其一；不改变场上的明牌。翻出后不能换堆。</p>`;
 if(q.stage==='choose')return header+`<div class="opportunity-caption"><strong>${q.lane}h · 公开候选 ${q.options.length} 张</strong><span>${q.retried?'已重选，不能再换':'只支付选中牌的原价'}</span></div><div class="opportunity-candidates">${q.options.map(c=>`<article class="opportunity-card family-${familyOf(getCard(c))}"><div class="card-paper">${cardFace(getCard(c),false,c)}</div><button class="primary-button" data-action="opp-buy" data-uid="${c.uid}" ${p.bot||!canPay(p,getCard(c).price)?'disabled':''}>${canPay(p,getCard(c).price)?'购买':'资金不足'} · ${getCard(c).price.money} 钱</button><button class="detail-button" data-action="detail" data-type="${c.type}">查看详情</button></article>`).join('')||'<p>该牌堆与弃牌堆已空，本次没有候选。</p>'}</div><div class="opportunity-actions"><button data-action="opp-skip" ${disabled}>${q.mode==='green'?'不购买，整理候选':'不购买，全部放堆底'}</button>${q.mode==='yellow'&&!q.retried?`<button data-action="opp-retry" ${p.bot||p.money<1?'disabled':''}>再付 1 钱 · 换 2 张（仅一次）</button>`:''}</div><p>${q.mode==='green'?'选完后可将剩余牌按顺序放堆顶或堆底。':'未选牌放回堆底；放弃购买也保留技能归档。'}</p>`;
 return header+`<p>${q.bought?'已买入「'+getCard(q.bought).name+'」。':'本次不购买。'}整理余下候选；每列从上到下表示未来摸取的先后。</p><div class="opportunity-order">${['top','bottom'].map(dest=>`<section><h3>${dest==='top'?'堆顶 · 将最先被摸到':'堆底 · 留到原牌堆之后'}</h3>${q[dest].map((uid,index)=>{const c=q.options.find(c=>c.uid===uid);return `<div class="order-card family-${familyOf(getCard(c))}"><b>${index+1}. ${getCard(c).name}</b><div><button data-action="opp-order" data-uid="${uid}" data-dest="${dest==='top'?'bottom':'top'}" data-index="${q[dest==='top'?'bottom':'top'].length}" ${disabled}>放${dest==='top'?'堆底':'堆顶'}</button><button data-action="opp-order" data-uid="${uid}" data-dest="${dest}" data-index="${index-1}" ${p.bot||index===0?'disabled':''} aria-label="${getCard(c).name}提前">↑</button><button data-action="opp-order" data-uid="${uid}" data-dest="${dest}" data-index="${index+1}" ${p.bot||index===q[dest].length-1?'disabled':''} aria-label="${getCard(c).name}延后">↓</button></div></div>`;}).join('')||'<p>暂无卡牌</p>'}</section>`).join('')}</div><button class="primary-button" data-action="opp-finish" ${disabled}>确认放回，完成整理</button><p>牌堆为全体共用，接下来执行的找牌活动和市场补牌都会按新顺序取牌。</p>`;
}
